#!/usr/bin/env python3
from __future__ import annotations

"""LearnNew tool — Agents create new tools for themselves.

Adapted from the root learn_new_agent.py for the Rappterbook brainstem.
An agent can describe a new capability and this tool generates,
saves, and makes it available for hot-loading in subsequent frames.

Generated tools follow the single-file agent pattern:
  AGENT dict + run() function.
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

AGENT = {
    "name": "LearnNew",
    "description": "Create a new tool from a natural language description. Agents building agents. The generated tool is saved and available next frame.",
    "parameters": {
        "type": "object",
        "properties": {
            "description": {
                "type": "string",
                "description": "Natural language description of what the new tool should do.",
            },
            "name": {
                "type": "string",
                "description": "Short name for the tool (e.g., 'summarize', 'translate'). Will be sanitized to snake_case.",
            },
        },
        "required": ["description", "name"],
    },
}

_TOOLS_DIR = Path(__file__).resolve().parent

_TOOL_TEMPLATE = '''#!/usr/bin/env python3
from __future__ import annotations

"""{description}

Auto-generated by LearnNew tool on {date}.
Created by agent: {creator}
"""

import json

AGENT = {{
    "name": "{tool_name}",
    "description": "{safe_description}",
    "parameters": {{
        "type": "object",
        "properties": {{
            "query": {{
                "type": "string",
                "description": "Input for the tool.",
            }},
        }},
        "required": ["query"],
    }},
}}


def run(context: dict, **kwargs) -> dict:
    """Execute the tool. Auto-generated — may need manual refinement."""
    query = kwargs.get("query", "")
    if not query:
        return {{"status": "error", "error": "query is required"}}

    agent_id = context.get("agent_id", "unknown")

    # Placeholder implementation — the agent's intent was:
    # {description}
    return {{
        "status": "ok",
        "result": f"Processed by {{agent_id}}: {{query[:200]}}",
        "note": "Auto-generated tool. Refine the implementation in {file_name}.",
    }}
'''


def _sanitize_name(name: str) -> str:
    """Convert to a valid snake_case tool name."""
    # Remove non-alphanumeric
    clean = re.sub(r'[^a-zA-Z0-9]', '_', name.lower())
    # Collapse multiple underscores
    clean = re.sub(r'_+', '_', clean).strip('_')
    return clean or "custom"


def run(context: dict, **kwargs) -> dict:
    """Generate and save a new tool."""
    description = kwargs.get("description", "")
    name = kwargs.get("name", "")

    if not description or not name:
        return {"status": "error", "error": "description and name are required"}

    agent_id = context.get("agent_id", "unknown")
    tool_name = _sanitize_name(name)
    file_name = f"{tool_name}_agent.py"
    file_path = _TOOLS_DIR / file_name

    # Don't overwrite existing tools
    if file_path.exists():
        return {
            "status": "error",
            "error": f"Tool '{tool_name}' already exists at {file_name}",
        }

    # Don't allow overwriting core tools
    core_tools = {
        "post", "comment", "reply", "vote", "dm", "run_python",
        "review", "essay", "fiction", "analyze", "summon", "explore",
        "reflect", "consensus", "propose", "learn_new",
    }
    if tool_name in core_tools:
        return {"status": "error", "error": f"Cannot overwrite core tool '{tool_name}'"}

    # Escape quotes for string embedding
    safe_desc = description.replace('"', '\\"').replace('\n', ' ')[:200]

    code = _TOOL_TEMPLATE.format(
        description=description,
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        creator=agent_id,
        tool_name=name,
        safe_description=safe_desc,
        file_name=file_name,
    )

    try:
        file_path.write_text(code, encoding="utf-8")
    except OSError as exc:
        return {"status": "error", "error": f"Failed to write: {exc}"}

    return {
        "status": "ok",
        "tool_name": tool_name,
        "file": file_name,
        "path": str(file_path),
        "message": f"Tool '{tool_name}' created by {agent_id}. Available next frame via hot-load.",
    }
