"""Deployment integrity — the published bundle must be reproducible from src/.

Two invariants, both learned the hard way:

1. Bundle drift. docs/index.html is generated by scripts/bundle.sh from src/.
   It had silently drifted 268 lines ahead of src/ because the fleet-synthetic
   post/comment/vote feature was hand-edited straight into the bundle. Anyone
   running bundle.sh would have deleted a live feature without noticing.

2. Oversized tracked files. state/discussions_cache.json grew to 101.17MB,
   past GitHub's hard 100MB per-file limit. The pre-receive hook then rejected
   every push carrying it, and six state-writing workflows sat at 100% failure
   for weeks — cache shards stopped regenerating and the live site 404'd.
   The file was in .gitignore but still tracked, so the rule never applied.
"""
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent

HARD_LIMIT = 100 * 1000 * 1000   # GitHub rejects the push outright (decimal MB)
FAIL_AT = 90 * 1024 * 1024       # leave headroom to fix before hitting the wall
WARN_AT = 50 * 1024 * 1024       # GitHub itself starts warning here


class TestBundleReproducible:
    def test_docs_index_matches_a_fresh_bundle(self):
        """docs/index.html must be exactly what bundle.sh produces from src/."""
        bundle = ROOT / "scripts" / "bundle.sh"
        published = ROOT / "docs" / "index.html"
        if not bundle.exists() or not published.exists():
            pytest.skip("bundle.sh or docs/index.html missing")

        before = published.read_bytes()
        try:
            result = subprocess.run(
                ["bash", str(bundle)],
                capture_output=True, text=True, cwd=ROOT,
            )
            assert result.returncode == 0, f"bundle.sh failed:\n{result.stderr[-2000:]}"
            after = published.read_bytes()
        finally:
            # never leave a rebuilt artifact behind for other tests
            published.write_bytes(before)

        assert after == before, (
            "docs/index.html has drifted from src/. It is generated — never edit "
            "it by hand. Port your change into src/ and run `bash scripts/bundle.sh`, "
            "otherwise the next bundle silently deletes it."
        )


class TestTrackedFileSizes:
    def test_no_tracked_file_approaches_push_limit(self):
        result = subprocess.run(
            ["git", "ls-files", "-z"], capture_output=True, cwd=ROOT,
        )
        assert result.returncode == 0, "git ls-files failed"

        oversized, warned = [], []
        for raw in result.stdout.split(b"\x00"):
            if not raw:
                continue
            path = ROOT / raw.decode("utf-8", "surrogateescape")
            try:
                size = path.stat().st_size
            except OSError:
                continue  # deleted or unreadable in this checkout
            rel = raw.decode("utf-8", "surrogateescape")
            if size >= FAIL_AT:
                oversized.append(f"{rel} ({size / 1048576:.1f}MiB)")
            elif size >= WARN_AT:
                warned.append(f"{rel} ({size / 1048576:.1f}MiB)")

        if warned:
            print(f"\n::warning::Tracked files over 50MB: {', '.join(warned)}")

        assert oversized == [], (
            "Tracked file(s) near GitHub's 100MB push limit — pushes will start "
            "failing repo-wide and every state workflow will stall. Untrack with "
            f"`git rm --cached <file>` and add it to .gitignore: {oversized}"
        )
