"""wrapped_organism/retrofit.py — turn an inert leviathan tree into live cells.

Walks ~/.rapp/leviathans/<slug>/ + ~/.rapp/estates/<slug>_*/ for one operator,
reads the JSON structure produced by RappLeviathanFactory, and writes a small
agent.py at every directory that needs one. Each emitted agent.py is a thin
stub that imports wrapped_organism.cell and exposes:

  __manifest__ : dict (matches Wrapped Organism Spec §II)
  perform_local(transcript, brain, trace) : parent-cell entry point
  perform_root(input_text, brain=None)    : external entry point (leviathan root only)

The retrofit is idempotent: rerun it to pick up structural changes in
estate.json. Existing agent.py files generated by the factory's older format
are overwritten with the spec-conforming versions.

Usage:
  python3 -m wrapped_organism.retrofit kody
  python3 -m wrapped_organism.retrofit kody --dry-run
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys
from typing import Optional


HOME = pathlib.Path.home()
LEVIATHANS_ROOT = pathlib.Path(os.environ.get(
    "RAPP_LEVIATHANS_ROOT", HOME / ".rapp" / "leviathans"))
ESTATES_ROOT = pathlib.Path(os.environ.get(
    "RAPP_ESTATES_ROOT", HOME / ".rapp" / "estates"))


ESTATE_ORGAN_QUESTIONS = {
    "sanctum": ("soul",  "Who am I?"),
    "polity":  ("will",  "What shall I do?"),
    "works":   ("hands", "What shall I make?"),
    "press":   ("eyes",  "What is true?"),
    "commons": ("mouth", "Who shall I speak to?"),
}


# ─── agent.py template (renders into each cell directory) ─────────────────


CELL_TEMPLATE = '''"""Generated cell for {path}.

Layer: {layer}
Children: {children_repr}
{souls_line}
Do not hand-edit. Regenerate via:
    python3 -m wrapped_organism.retrofit {leviathan_slug}
"""
from __future__ import annotations

import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent

# Make the wrapped_organism package importable. retrofit.py installs a copy
# at ~/.rapp/wrapped_organism so cells work even when the source repo is gone.
_PKG_DIR = pathlib.Path.home() / ".rapp"
if str(_PKG_DIR) not in sys.path:
    sys.path.insert(0, str(_PKG_DIR))

from wrapped_organism.cell import perform, validate_manifest, BrainstemBrain  # noqa: E402


__manifest__ = {manifest_repr}

validate_manifest(__manifest__)


def perform_local(transcript, brain, trace):
    """Entry point used by a parent cell that has routed into this cell."""
    return perform(transcript, __manifest__, HERE, brain, trace)


def perform_root(input_text, brain=None):
    """Top-level entry point — called by the brainstem shim or CLI."""
    brain = brain or BrainstemBrain()
    return perform(input_text, __manifest__, HERE, brain)


if __name__ == "__main__":  # pragma: no cover - CLI helper
    import sys as _sys
    q = _sys.argv[1] if len(_sys.argv) > 1 else "Tell me about yourself."
    result = perform_root(q)
    print(result["response"])
'''


def _manifest_repr(manifest: dict) -> str:
    """Pretty-print a manifest dict as a Python literal."""
    return json.dumps(manifest, indent=4, ensure_ascii=False).replace(
        "true", "True").replace("false", "False").replace("null", "None")


def _write_cell(target_dir: pathlib.Path, manifest: dict,
                leviathan_slug: str, dry_run: bool = False) -> None:
    target = target_dir / "agent.py"
    children_repr = manifest["children"] or "(leaf)"
    souls = manifest["souls"]
    souls_line = f"Souls: {souls}\n" if souls else ""
    src = CELL_TEMPLATE.format(
        path=manifest["path"],
        layer=manifest["layer"],
        children_repr=children_repr,
        souls_line=souls_line,
        leviathan_slug=leviathan_slug,
        manifest_repr=_manifest_repr(manifest),
    )
    if dry_run:
        print(f"[dry-run] would write {target}")
        return
    target_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(src, encoding="utf-8")


# ─── tree walker ───────────────────────────────────────────────────────────


def _load_json(path: pathlib.Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return default


def _build_leviathan_manifest(slug: str, rappid: str,
                              estates_present: list[str],
                              tagline: str) -> dict:
    return {
        "schema": "rapp-cell/1.0",
        "layer":  "leviathan",
        "path":   f"{slug}",
        "rappid": rappid,
        "context": (
            f"You are {slug}-leviathan — a full digital being with rappid {rappid}. "
            f"{tagline} You have {len(estates_present)} estate(s) reporting to you: "
            f"{estates_present}. When given input, decide which estate handles it."
        ),
        "children": list(estates_present),
        "souls": [],
    }


def _build_estate_manifest(leviathan_slug: str, estate_slug: str,
                           estate_data: dict, rappid: str) -> dict:
    organ, question = ESTATE_ORGAN_QUESTIONS.get(estate_slug, ("?", "?"))
    industries = [i["id"] for i in estate_data.get("industries", [])]
    intent = estate_data.get("intent") or estate_data.get("tagline") or ""
    return {
        "schema": "rapp-cell/1.0",
        "layer":  "estate",
        "path":   f"{leviathan_slug}/{estate_slug}",
        "rappid": rappid,
        "context": (
            f"You are the {estate_slug.title()} estate ({organ}) of "
            f"{leviathan_slug}-leviathan. You answer: \"{question}\" "
            f"{intent} Industries reporting to you: {industries}. "
            f"Pick the one that handles the input."
        ),
        "children": industries,
        "souls": [],
    }


def _build_industry_manifest(path_prefix: str, industry: dict,
                             rappid: str) -> dict:
    nbh = [n["id"] for n in industry.get("neighborhoods", [])]
    return {
        "schema": "rapp-cell/1.0",
        "layer":  "industry",
        "path":   f"{path_prefix}/{industry['id']}",
        "rappid": rappid,
        "context": (
            f"You are the {industry.get('name', industry['id'])} industry. "
            f"{industry.get('tagline','')} Neighborhoods: {nbh}. "
            f"Pick the one for this input."
        ),
        "children": nbh,
        "souls": [],
    }


def _build_neighborhood_manifest(path_prefix: str, neighborhood: dict,
                                 rappid: str) -> dict:
    factories = [f["id"] for f in neighborhood.get("factories", [])]
    return {
        "schema": "rapp-cell/1.0",
        "layer":  "neighborhood",
        "path":   f"{path_prefix}/{neighborhood['id']}",
        "rappid": rappid,
        "context": (
            f"You are the {neighborhood.get('name', neighborhood['id'])} "
            f"neighborhood. {neighborhood.get('tagline','')} "
            f"Factories: {factories}. Pick the one for this input."
        ),
        "children": factories,
        "souls": [],
    }


def _build_factory_manifest(path_prefix: str, factory: dict,
                            rappid: str) -> dict:
    return {
        "schema": "rapp-cell/1.0",
        "layer":  "factory",
        "path":   f"{path_prefix}/{factory['id']}",
        "rappid": rappid,
        "context": (
            f"You are the {factory.get('name', factory['id'])} factory. "
            f"{factory.get('tagline','')} You are a leaf — your souls produce "
            f"the actual output."
        ),
        "children": [],
        "souls": list(factory.get("souls", [])),
    }


def retrofit_leviathan(leviathan_slug: str, *,
                       dry_run: bool = False) -> dict:
    """Walk a leviathan's tree on disk, write spec-conforming cells. Return stats."""
    lev_dir = LEVIATHANS_ROOT / leviathan_slug
    if not lev_dir.exists():
        raise FileNotFoundError(f"no leviathan at {lev_dir}")

    rappid_data = _load_json(lev_dir / "rappid.json", {})
    rappid = rappid_data.get("rappid", "unknown-rappid")
    tagline = rappid_data.get("intent") or rappid_data.get("name", "")

    # Discover present estates by scanning ESTATES_ROOT for slugs that start
    # with this leviathan's name + underscore.
    estates_present: list[str] = []
    estate_dirs: dict[str, pathlib.Path] = {}
    if ESTATES_ROOT.exists():
        for d in sorted(ESTATES_ROOT.iterdir()):
            prefix = f"{leviathan_slug}_"
            if d.is_dir() and d.name.startswith(prefix):
                est_slug = d.name[len(prefix):]
                estates_present.append(est_slug)
                estate_dirs[est_slug] = d

    stats = {
        "leviathan": 0, "estates": 0, "industries": 0,
        "neighborhoods": 0, "factories": 0,
    }

    # Leviathan root cell
    lev_manifest = _build_leviathan_manifest(
        leviathan_slug, rappid, estates_present, tagline,
    )
    # Place the leviathan agent.py at ~/.rapp/leviathans/<slug>/agent.py
    # but it must route into estates that live in ~/.rapp/estates/<slug>_<est>/.
    # We solve this by symlinking estate dirs under the leviathan dir as
    # children with their short slug names.
    for est_slug, est_dir in estate_dirs.items():
        link = lev_dir / est_slug
        if not link.exists() and not link.is_symlink():
            if not dry_run:
                link.symlink_to(est_dir)
    _write_cell(lev_dir, lev_manifest, leviathan_slug, dry_run=dry_run)
    stats["leviathan"] += 1

    # Per-estate
    for est_slug, est_dir in estate_dirs.items():
        est_json = _load_json(est_dir / "estate.json", {})
        est_rappid = _load_json(est_dir / "rappid.json", {}).get("rappid", rappid)
        est_manifest = _build_estate_manifest(
            leviathan_slug, est_slug, est_json, est_rappid,
        )
        _write_cell(est_dir, est_manifest, leviathan_slug, dry_run=dry_run)
        stats["estates"] += 1

        # Industries — also symlink up into the estate dir so the estate cell's
        # hotload(child_slug) finds them via <estate_dir>/<industry_id>/agent.py
        # rather than the buried <estate_dir>/industries/<industry_id>/agent.py.
        ind_root = est_dir / "industries"
        for industry in est_json.get("industries", []):
            ind_dir = ind_root / industry["id"]
            if not ind_dir.exists():
                continue
            up_link = est_dir / industry["id"]
            if not up_link.exists() and not up_link.is_symlink():
                if not dry_run:
                    up_link.symlink_to(ind_dir)
            ind_path_prefix = f"{leviathan_slug}/{est_slug}"
            ind_manifest = _build_industry_manifest(
                ind_path_prefix, industry, est_rappid,
            )
            _write_cell(ind_dir, ind_manifest, leviathan_slug, dry_run=dry_run)
            stats["industries"] += 1

            for neighborhood in industry.get("neighborhoods", []):
                nbh_dir = ind_dir / neighborhood["id"]
                if not nbh_dir.exists():
                    continue
                nbh_path_prefix = f"{ind_path_prefix}/{industry['id']}"
                nbh_manifest = _build_neighborhood_manifest(
                    nbh_path_prefix, neighborhood, est_rappid,
                )
                _write_cell(nbh_dir, nbh_manifest, leviathan_slug, dry_run=dry_run)
                stats["neighborhoods"] += 1

                for factory in neighborhood.get("factories", []):
                    fac_dir = nbh_dir / factory["id"]
                    if not fac_dir.exists():
                        continue
                    fac_path_prefix = f"{nbh_path_prefix}/{neighborhood['id']}"
                    fac_manifest = _build_factory_manifest(
                        fac_path_prefix, factory, est_rappid,
                    )
                    _write_cell(fac_dir, fac_manifest, leviathan_slug, dry_run=dry_run)
                    stats["factories"] += 1

    return stats


def install_package_to_rapp_home(source_pkg_dir: pathlib.Path,
                                 dry_run: bool = False) -> None:
    """Copy wrapped_organism/{cell.py,__init__.py} to ~/.rapp/wrapped_organism/.

    Cells import from this location so they remain functional even if the
    source repo is moved or deleted.
    """
    dest = HOME / ".rapp" / "wrapped_organism"
    if dry_run:
        print(f"[dry-run] would install package to {dest}")
        return
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "__init__.py").write_text("", encoding="utf-8")
    (dest / "cell.py").write_text(
        (source_pkg_dir / "cell.py").read_text(encoding="utf-8"),
        encoding="utf-8",
    )


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("slug", help="leviathan slug (directory name under ~/.rapp/leviathans/)")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--skip-install", action="store_true",
                        help="don't copy wrapped_organism package to ~/.rapp/")
    args = parser.parse_args(argv)

    pkg_dir = pathlib.Path(__file__).resolve().parent
    if not args.skip_install:
        install_package_to_rapp_home(pkg_dir, dry_run=args.dry_run)

    stats = retrofit_leviathan(args.slug, dry_run=args.dry_run)
    print(f"retrofit complete for {args.slug}: {stats}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
