"""
Scans the local agents/ folder for *_agent.py files. For each one, parses the module-level docstring (using Python's ast module, stdlib-only) and extracts the first non-empty line as a one-line summary. If no docstring exists, falls back to the class docstring of the first class extending BasicAgent, then to "(no description)". Prints a clean GitHub-flavored markdown table with three columns: Agent (filename without _agent.py suffix), Class (the BasicAgent subclass name if found), and Summary (the one-line description, truncated to 80 chars). Sorts rows alphabetically by agent name. Also prints a footer line with the total count, e.g. "_12 agents discovered._". Handles missing agents/ folder gracefully with a clear error message. Returns the markdown string from perform() so it can be piped or saved.

Auto-generated by LearnNewAgent on 2026-05-02 23:09.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
from pathlib import Path

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/agentinventory",
    "version": "1.0.0",
    "display_name": "Agentinventory",
    "description": "Scans the local agents/ folder for *_agent.py files. For each one, parses the module-level docstring (using Python's ast module, stdlib-only) and extracts the first non-empty line as a one-line summar",
    "author": "rapp",
    "tags": ["filesystem"],
    "category": "devtools",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"path": "example path"}},
}


class AgentinventoryAgent(BasicAgent):
    def __init__(self):
        self.name = 'Agentinventory'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number or count value."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        import os
        import ast
        import json

        try:
            folder = kwargs.get('folder', 'agents')
            truncate = kwargs.get('truncate', 80)

            if not os.path.isdir(folder):
                msg = f"Folder '{folder}' not found."
                print(f"**Error:** {msg}")
                return json.dumps({'status': 'error', 'message': msg})

            rows = []
            for fname in os.listdir(folder):
                if not fname.endswith('_agent.py'):
                    continue
                fpath = os.path.join(folder, fname)
                agent_name = fname[:-len('_agent.py')]
                class_name = ''
                summary = '(no description)'

                try:
                    with open(fpath, 'r', encoding='utf-8') as f:
                        source = f.read()
                    tree = ast.parse(source)

                    mod_doc = ast.get_docstring(tree)

                    first_basic_class = None
                    first_basic_doc = None
                    for node in tree.body:
                        if isinstance(node, ast.ClassDef):
                            extends_basic = False
                            for base in node.bases:
                                base_name = ''
                                if isinstance(base, ast.Name):
                                    base_name = base.id
                                elif isinstance(base, ast.Attribute):
                                    base_name = base.attr
                                if base_name == 'BasicAgent':
                                    extends_basic = True
                                    break
                            if extends_basic and first_basic_class is None:
                                first_basic_class = node.name
                                first_basic_doc = ast.get_docstring(node)

                    if first_basic_class:
                        class_name = first_basic_class

                    chosen_doc = mod_doc if mod_doc else first_basic_doc
                    if chosen_doc:
                        for line in chosen_doc.splitlines():
                            line = line.strip()
                            if line:
                                summary = line
                                break

                    if len(summary) > truncate:
                        summary = summary[:truncate - 3] + '...'

                    summary = summary.replace('|', '\\|')
                except Exception as parse_err:
                    summary = f"(parse error: {parse_err})"
                    if len(summary) > truncate:
                        summary = summary[:truncate - 3] + '...'

                rows.append((agent_name, class_name, summary))

            rows.sort(key=lambda r: r[0].lower())

            lines = []
            lines.append('| Agent | Class | Summary |')
            lines.append('|---|---|---|')
            for agent_name, class_name, summary in rows:
                lines.append(f'| {agent_name} | {class_name} | {summary} |')
            lines.append('')
            lines.append(f'_{len(rows)} agents discovered._')

            md = '\n'.join(lines)
            print(md)

            return json.dumps({
                'status': 'ok',
                'count': len(rows),
                'markdown': md,
                'agents': [
                    {'agent': a, 'class': c, 'summary': s}
                    for a, c, s in rows
                ]
            })
        except Exception as e:
            return json.dumps({'status': 'error', 'message': str(e)})


if __name__ == "__main__":
    a = AgentinventoryAgent()
    print(a.perform(query="test"))