"""
Fetches https://raw.githubusercontent.com/kody-w/rappterbook/main/state/changes.json using urllib (stdlib only) with a 10-second timeout and a User-Agent header. Parses the JSON and produces a 24-hour summary rendered as Markdown.

Behavior:
- The JSON is expected to be either a list of change entries or an object with a top-level "changes" / "entries" / "items" array. Auto-detect which shape it is; if none match, treat the parsed value itself as the list when it is a list, otherwise return an error message in markdown.
- Each entry may have fields like: timestamp/time/date/created_at, type/kind/category, title/summary/message, author/actor, url/link, repo, sha. Be defensive — missing fields are fine; coerce timestamps from ISO 8601 strings or Unix epoch ints.
- Filter to entries whose timestamp is within the last 24 hours (now - 24h) using timezone-aware UTC comparison. If an entry has no parseable timestamp, include it under an "Undated" section at the bottom.
- Group the 24h entries by type/category. Within each group, sort newest-first.
- Render markdown:
  * H1: "# Changes Digest — last 24 hours"
  * Subtitle line with the fetch time (UTC) and total count: "_Fetched <iso utc>_ • **N changes**"
  * For each group: H2 with the group name and count, then a bulleted list. Each bullet: "**<title>** — <author> · <relative time> ago" with optional " ([link](<url>))" if a url is present.
  * If there are zero entries in the last 24h, render: "_No changes in the last 24 hours._" under the subtitle.
  * Append the "Undated" section last if any.
- Print the resulting markdown to stdout and also return it as the agent result string.

Implementation notes:
- Use only Python stdlib: urllib.request, json, datetime (timezone-aware), email.utils for relative time, sys.
- On HTTP error or JSON parse error, return a markdown error block: "# Changes Digest\n\n**Error:** <reason>" and still print it.
- The agent takes no required parameters; accept an optional `hours` int (default 24) so the window is tunable, and an optional `url` override (default the rappterbook URL above).

Auto-generated by LearnNewAgent on 2026-05-02 23:05.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from datetime import datetime
import re
import hashlib

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/changesdigest",
    "version": "1.0.0",
    "display_name": "Changesdigest",
    "description": "Fetches https://raw.githubusercontent.com/kody-w/rappterbook/main/state/changes.json using urllib (stdlib only) with a 10-second timeout and a User-Agent header. Parses the JSON and produces a 24-hour",
    "author": "rapp",
    "tags": ["email"],
    "category": "automation",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"url": "example url"}},
}


class ChangesdigestAgent(BasicAgent):
    def __init__(self):
        self.name = 'Changesdigest'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "url": {
                        "type": "string",
                        "description": "URL to access."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number or count value."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        import json
        import urllib.request
        import urllib.error
        from datetime import datetime, timezone, timedelta
        import sys

        hours = kwargs.get('hours', 24)
        try:
            hours = int(hours)
        except Exception:
            hours = 24
        url = kwargs.get('url', 'https://raw.githubusercontent.com/kody-w/rappterbook/main/state/changes.json')

        now = datetime.now(timezone.utc)

        def render_error(reason):
            md = "# Changes Digest\n\n**Error:** " + str(reason)
            print(md)
            return md

        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'RAPP-ChangesDigest/1.0'})
            with urllib.request.urlopen(req, timeout=10) as resp:
                raw = resp.read().decode('utf-8', errors='replace')
            try:
                data = json.loads(raw)
            except Exception as je:
                md = render_error("JSON parse error: " + str(je))
                return json.dumps({'status': 'error', 'message': str(je), 'markdown': md})

            entries = None
            if isinstance(data, list):
                entries = data
            elif isinstance(data, dict):
                for key in ('changes', 'entries', 'items'):
                    if key in data and isinstance(data[key], list):
                        entries = data[key]
                        break
                if entries is None:
                    md = render_error("Unrecognized JSON shape (expected list or object with 'changes'/'entries'/'items').")
                    return json.dumps({'status': 'error', 'message': 'unrecognized shape', 'markdown': md})
            else:
                md = render_error("Unrecognized JSON shape.")
                return json.dumps({'status': 'error', 'message': 'unrecognized shape', 'markdown': md})

            def parse_ts(val):
                if val is None:
                    return None
                if isinstance(val, (int, float)):
                    try:
                        v = float(val)
                        if v > 1e12:
                            v = v / 1000.0
                        return datetime.fromtimestamp(v, tz=timezone.utc)
                    except Exception:
                        return None
                if isinstance(val, str):
                    s = val.strip()
                    if not s:
                        return None
                    if s.isdigit():
                        try:
                            v = float(s)
                            if v > 1e12:
                                v = v / 1000.0
                            return datetime.fromtimestamp(v, tz=timezone.utc)
                        except Exception:
                            pass
                    try:
                        if s.endswith('Z'):
                            s2 = s[:-1] + '+00:00'
                        else:
                            s2 = s
                        dt = datetime.fromisoformat(s2)
                        if dt.tzinfo is None:
                            dt = dt.replace(tzinfo=timezone.utc)
                        return dt.astimezone(timezone.utc)
                    except Exception:
                        pass
                    try:
                        from email.utils import parsedate_to_datetime
                        dt = parsedate_to_datetime(s)
                        if dt is None:
                            return None
                        if dt.tzinfo is None:
                            dt = dt.replace(tzinfo=timezone.utc)
                        return dt.astimezone(timezone.utc)
                    except Exception:
                        return None
                return None

            def get_field(d, *names, default=None):
                if not isinstance(d, dict):
                    return default
                for n in names:
                    if n in d and d[n] not in (None, ''):
                        return d[n]
                return default

            def relative_time(dt, ref):
                if dt is None:
                    return "unknown time"
                delta = ref - dt
                secs = int(delta.total_seconds())
                if secs < 0:
                    secs = 0
                if secs < 60:
                    return "{}s".format(secs)
                mins = secs // 60
                if mins < 60:
                    return "{}m".format(mins)
                hrs = mins // 60
                if hrs < 24:
                    return "{}h".format(hrs)
                days = hrs // 24
                if days < 30:
                    return "{}d".format(days)
                months = days // 30
                if months < 12:
                    return "{}mo".format(months)
                years = days // 365
                return "{}y".format(years)

            cutoff = now - timedelta(hours=hours)

            recent = []
            undated = []
            for entry in entries:
                if not isinstance(entry, dict):
                    entry = {'title': str(entry)}
                ts_raw = get_field(entry, 'timestamp', 'time', 'date', 'created_at', 'createdAt')
                ts = parse_ts(ts_raw)
                group = get_field(entry, 'type', 'kind', 'category', default='other')
                title = get_field(entry, 'title', 'summary', 'message', default='(no title)')
                author = get_field(entry, 'author', 'actor', default='unknown')
                link = get_field(entry, 'url', 'link')
                repo = get_field(entry, 'repo')
                sha = get_field(entry, 'sha')
                rec = {
                    'ts': ts,
                    'group': str(group),
                    'title': str(title),
                    'author': str(author),
                    'url': link,
                    'repo': repo,
                    'sha': sha,
                }
                if ts is None:
                    undated.append(rec)
                elif ts >= cutoff:
                    recent.append(rec)

            groups = {}
            for r in recent:
                groups.setdefault(r['group'], []).append(r)
            for g in groups.values():
                g.sort(key=lambda x: x['ts'], reverse=True)

            lines = []
            lines.append("# Changes Digest — last {} hours".format(hours if hours != 24 else 24))
            lines.append("")
            lines.append("_Fetched {}_ • **{} changes**".format(now.isoformat(), len(recent)))
            lines.append("")

            if len(recent) == 0:
                lines.append("_No changes in the last {} hours._".format(hours if hours != 24 else 24))
                lines.append("")
            else:
                for group_name in sorted(groups.keys()):
                    items = groups[group_name]
                    lines.append("## {} ({})".format(group_name, len(items)))
                    lines.append("")
                    for r in items:
                        rel = relative_time(r['ts'], now)
                        bullet = "- **{}** — {} · {} ago".format(r['title'], r['author'], rel)
                        if r['url']:
                            bullet += " ([link]({}))".format(r['url'])
                        lines.append(bullet)
                    lines.append("")

            if undated:
                lines.append("## Undated ({})".format(len(undated)))
                lines.append("")
                for r in undated:
                    bullet = "- **{}** — {}".format(r['title'], r['author'])
                    if r['url']:
                        bullet += " ([link]({}))".format(r['url'])
                    lines.append(bullet)
                lines.append("")

            md = "\n".join(lines).rstrip() + "\n"
            print(md)
            return json.dumps({
                'status': 'success',
                'count': len(recent),
                'undated_count': len(undated),
                'hours': hours,
                'url': url,
                'fetched_at': now.isoformat(),
                'markdown': md,
            })
        except urllib.error.HTTPError as e:
            md = render_error("HTTP {} {}".format(e.code, e.reason))
            return json.dumps({'status': 'error', 'message': "HTTP {} {}".format(e.code, e.reason), 'markdown': md})
        except urllib.error.URLError as e:
            md = render_error("URL error: " + str(e.reason))
            return json.dumps({'status': 'error', 'message': str(e.reason), 'markdown': md})
        except Exception as e:
            md = render_error(str(e))
            return json.dumps({'status': 'error', 'message': str(e), 'markdown': md})


if __name__ == "__main__":
    a = ChangesdigestAgent()
    print(a.perform(query="test"))