"""
Reads the Continuum log at state/continuum/log.jsonl (relative to repo/cwd; fall back to ~/.brainstem/state/continuum/log.jsonl if missing) and prints a markdown status report. Each line in the log is a JSON object with fields like {ts, task, outcome, summary, tick} where outcome is one of "success", "skip", "crash" (be tolerant of variants like "ok"/"shipped" → success, "skipped"/"noop" → skip, "error"/"failed" → crash; unknown outcomes count as "other"). The agent must:

1. Open the log file safely; if it does not exist or is empty, print a friendly markdown notice ("# Continuum Status\n\nNo ticks logged yet.") and return.
2. Stream-parse line by line with json.loads inside try/except so a single corrupt line does not abort the report — count corrupt lines under a "malformed" tally.
3. Compute totals: total ticks completed, and a breakdown of success / skip / crash / other counts. Also compute the timestamp of the first and last tick if available.
4. Render a markdown report with these sections:
   - "# Continuum Status"
   - A summary line: "**N ticks** — ✅ success, ⏭ skip, 💥 crash, ❓ other (M malformed lines ignored)" — omit malformed clause when zero.
   - Optional "First tick: <ts>  ·  Last tick: <ts>" line when timestamps are present.
   - "## Last 5 summaries" followed by a bulleted list of the most recent 5 entries in reverse chronological order, each formatted as "- `<outcome-emoji>` **<task>** — <summary> _(<ts>)_". Use ✅/⏭/💥/❓ for the emoji. Truncate task to 60 chars and summary to 140 chars with an ellipsis if longer. If fewer than 5 entries, show what exists.
5. Print the markdown to stdout (the BasicAgent perform() should return the string as well so callers can capture it).

Stdlib-only: json, os, pathlib, datetime. No external deps. Keep the agent under ~120 lines. Include a __main__ guard so `python agents/continuum_status_agent.py` runs it directly.

Auto-generated by LearnNewAgent on 2026-05-03 05:51.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
from datetime import datetime
from pathlib import Path

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/continuumstatus",
    "version": "1.0.0",
    "display_name": "Continuumstatus",
    "description": "Reads the Continuum log at state/continuum/log.jsonl (relative to repo/cwd; fall back to ~/.brainstem/state/continuum/log.jsonl if missing) and prints a markdown status report. Each line in the log is",
    "author": "rapp",
    "tags": ["filesystem"],
    "category": "devtools",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"path": "example path"}},
}


class ContinuumstatusAgent(BasicAgent):
    def __init__(self):
        self.name = 'Continuumstatus'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number or count value."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        try:
            import json, os
            from pathlib import Path
            from datetime import datetime

            primary = Path('state/continuum/log.jsonl')
            fallback = Path.home() / '.brainstem' / 'state' / 'continuum' / 'log.jsonl'
            log_path = primary if primary.exists() else fallback

            header = "# Continuum Status"

            if not log_path.exists() or log_path.stat().st_size == 0:
                report = f"{header}\n\nNo ticks logged yet."
                print(report)
                return json.dumps({'status': 'ok', 'report': report, 'ticks': 0})

            success_aliases = {'success', 'ok', 'shipped'}
            skip_aliases = {'skip', 'skipped', 'noop'}
            crash_aliases = {'crash', 'error', 'failed'}

            counts = {'success': 0, 'skip': 0, 'crash': 0, 'other': 0}
            malformed = 0
            entries = []
            first_ts = None
            last_ts = None

            with open(log_path, 'r', encoding='utf-8', errors='replace') as f:
                for raw in f:
                    line = raw.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                    except Exception:
                        malformed += 1
                        continue
                    if not isinstance(obj, dict):
                        malformed += 1
                        continue
                    raw_outcome = str(obj.get('outcome', '')).strip().lower()
                    if raw_outcome in success_aliases:
                        bucket = 'success'
                    elif raw_outcome in skip_aliases:
                        bucket = 'skip'
                    elif raw_outcome in crash_aliases:
                        bucket = 'crash'
                    else:
                        bucket = 'other'
                    counts[bucket] += 1
                    ts = obj.get('ts')
                    if ts:
                        if first_ts is None:
                            first_ts = ts
                        last_ts = ts
                    entries.append({
                        'ts': ts,
                        'task': str(obj.get('task', '')),
                        'summary': str(obj.get('summary', '')),
                        'bucket': bucket,
                    })

            total = sum(counts.values())
            emoji_map = {'success': '✅', 'skip': '⏭', 'crash': '💥', 'other': '❓'}

            summary_line = (
                f"**{total} ticks** — "
                f"✅ {counts['success']} success, "
                f"⏭ {counts['skip']} skip, "
                f"💥 {counts['crash']} crash, "
                f"❓ {counts['other']} other"
            )
            if malformed:
                summary_line += f" ({malformed} malformed lines ignored)"

            lines = [header, "", summary_line, ""]

            if first_ts and last_ts:
                lines.append(f"First tick: {first_ts}  ·  Last tick: {last_ts}")
                lines.append("")

            lines.append("## Last 5 summaries")
            lines.append("")

            def truncate(s, n):
                s = s if s is not None else ''
                if len(s) > n:
                    return s[: n - 1] + '…'
                return s

            recent = list(reversed(entries[-5:]))
            if not recent:
                lines.append("_No entries._")
            else:
                for e in recent:
                    em = emoji_map.get(e['bucket'], '❓')
                    task = truncate(e['task'], 60)
                    summ = truncate(e['summary'], 140)
                    ts_str = e['ts'] if e['ts'] else ''
                    lines.append(f"- `{em}` **{task}** — {summ} _({ts_str})_")

            report = "\n".join(lines)
            print(report)
            return json.dumps({
                'status': 'ok',
                'report': report,
                'ticks': total,
                'counts': counts,
                'malformed': malformed,
                'first_ts': first_ts,
                'last_ts': last_ts,
            })
        except Exception as e:
            import json
            return json.dumps({'status': 'error', 'message': str(e)})


if __name__ == "__main__":
    a = ContinuumstatusAgent()
    print(a.perform(query="test"))