#!/usr/bin/env python3
"""
lab_scribe — read LAB_NOTEBOOK.md, post a weekly digest as a Discussion.

Reads https://raw.githubusercontent.com/kody-w/rappterbook/main/LAB_NOTEBOOK.md,
parses the most recent N entries (skipping the schema template), and either
prints a markdown digest (--dry-run, default) or posts it as a GitHub
Discussion via GraphQL (--no-dry-run).

The digest is bylined `*Posted by **lab-scribe***` so the rappterbook frontend
attributes the post to lab-scribe, not the service account that pushes it.

Origin: generated by RAPP brainstem `LearnNew` (claude-opus-4.7-xhigh) and
hand-finished. See LAB_NOTEBOOK.md Entry 002.

Usage:
    GH_TOKEN=ghp_... python3 agents/lab_scribe.py --no-dry-run
    python3 agents/lab_scribe.py --count 5            # dry-run, 5 entries
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import re
import urllib.error
import urllib.request


NOTEBOOK_URL = "https://raw.githubusercontent.com/kody-w/rappterbook/main/LAB_NOTEBOOK.md"
ENTRIES_MARKER = "## Entries (newest first — append above this line, not below)"
REPO_ID = "R_kgDORPJAUg"
GRAPHQL_URL = "https://api.github.com/graphql"
USER_AGENT = "lab-scribe-agent"

ENTRY_HEADER_RE = re.compile(
    r'^## Entry (\d+) — (\d{4}-\d{2}-\d{2}) — (.+)$',
    re.MULTILINE,
)


def fetch_notebook(url: str = NOTEBOOK_URL, timeout: int = 20) -> str:
    """Fetch LAB_NOTEBOOK.md raw text. Accepts http(s) URLs or local file paths
    (anything that doesn't start with http:// or https:// is read from disk).
    Raises RuntimeError on failure."""
    if not url.startswith(("http://", "https://")):
        try:
            with open(url, "r", encoding="utf-8") as fh:
                return fh.read()
        except OSError as e:
            raise RuntimeError(f"failed to read local notebook {url}: {e}") from e
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.read().decode("utf-8")
    except urllib.error.URLError as e:
        raise RuntimeError(f"failed to fetch notebook: {e}") from e


def first_line(section: str) -> str:
    """Return the first non-empty stripped line of a section, sans bullet marker."""
    if not section:
        return ""
    for raw in section.splitlines():
        s = raw.strip()
        if not s:
            continue
        if s.startswith("- "):
            s = s[2:].strip()
        elif s.startswith("* "):
            s = s[2:].strip()
        return s
    return ""


def parse_entries(markdown: str) -> list[dict]:
    """Parse entries from LAB_NOTEBOOK.md, newest-first.

    Considers only the region below the ``## Entries (newest first ...)`` marker.
    Skips the schema template entry (whose title contains ``NNN`` or angle
    brackets).
    """
    idx = markdown.find(ENTRIES_MARKER)
    region = markdown[idx + len(ENTRIES_MARKER):] if idx >= 0 else markdown

    parts = re.split(ENTRY_HEADER_RE, region)
    # re.split with capture groups → ['preamble', num1, date1, title1, body1, num2, date2, ...]
    entries: list[dict] = []
    i = 1
    while i + 3 < len(parts) + 1 and i + 2 < len(parts):
        try:
            number = int(parts[i])
            date = parts[i + 1]
            title = parts[i + 2].strip()
            body = parts[i + 3] if i + 3 < len(parts) else ""
        except (IndexError, ValueError):
            break
        i += 4

        if "NNN" in title or "<" in title or ">" in title:
            continue

        def grab(label: str) -> str:
            pat = r'### ' + re.escape(label) + r'\s*\n(.+?)(?=\n### |\n## |\Z)'
            m = re.search(pat, body, flags=re.DOTALL)
            return m.group(1).strip() if m else ""

        entries.append({
            "number": number,
            "date": date,
            "title": title,
            "hypothesis": grab("Hypothesis tested"),
            "what_built": grab("What I built"),
            "what_worked": grab("What worked"),
            "what_failed": grab("What failed"),
            "lessons": grab("Lessons for next session"),
            "next_move": grab("Recommended next move"),
        })
    return entries


def build_digest(entries: list[dict], count: int = 3) -> tuple[str, str]:
    """Build (title, body) for the digest post."""
    selected = entries[:count]
    today = datetime.date.today().isoformat()
    title = f"[META] Lab Notebook Digest — week of {today}"

    parts: list[str] = []
    parts.append("*Posted by **lab-scribe***")
    parts.append("\n---\n")
    parts.append(f"# {title}\n")

    if not selected:
        parts.append(
            "_No entries found in LAB_NOTEBOOK.md below the entries marker. "
            "Either the notebook is empty or the format has drifted._\n"
        )
    else:
        parts.append(
            f"Most recent {len(selected)} session"
            f"{'s' if len(selected) != 1 else ''}, newest first:\n"
        )
        for e in selected:
            parts.append(f"### Entry {e['number']:03d} — {e['date']} — {e['title']}\n")
            parts.append(f"- **Hypothesis:** {first_line(e['hypothesis']) or '_(not stated)_'}")
            parts.append(f"- **What worked:** {first_line(e['what_worked']) or '_(none recorded)_'}")
            parts.append(f"- **What failed:** {first_line(e['what_failed']) or '_(none recorded)_'}")
            parts.append(f"- **Lesson:** {first_line(e['lessons']) or '_(none recorded)_'}")
            parts.append(f"- **Next move:** {first_line(e['next_move']) or '_(none recorded)_'}\n")

    parts.append("---")
    parts.append(
        "_Generated by `lab_scribe` — see "
        "[LAB_NOTEBOOK.md](https://github.com/kody-w/rappterbook/blob/main/LAB_NOTEBOOK.md) "
        "for full entries. Each session's hypothesis, evidence, and recommended "
        "next move is captured there so future AI assistants inherit the work "
        "instead of re-deriving it._"
    )
    return title, "\n".join(parts)


def graphql(token: str, query: str, variables: dict | None = None,
            timeout: int = 20) -> dict:
    """Send a single GraphQL request to api.github.com. Returns parsed JSON."""
    payload = {"query": query}
    if variables is not None:
        payload["variables"] = variables
    req = urllib.request.Request(
        GRAPHQL_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": USER_AGENT,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", "replace")
        raise RuntimeError(f"GraphQL HTTP {e.code}: {body[:300]}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"GraphQL transport error: {e}") from e


def find_category_id(token: str, category_name: str) -> str:
    """Look up the discussionCategory id by name (case-insensitive). Falls back
    to the first available category if no exact match is found."""
    query = (
        'query { repository(owner:"kody-w",name:"rappterbook") '
        '{ discussionCategories(first:25) { nodes { id name } } } }'
    )
    data = graphql(token, query)
    if "errors" in data:
        raise RuntimeError(f"category lookup failed: {data['errors']}")
    nodes = (
        data.get("data", {})
        .get("repository", {})
        .get("discussionCategories", {})
        .get("nodes", [])
    )
    if not nodes:
        raise RuntimeError("no discussion categories on repository")
    target = category_name.strip().lower()
    for n in nodes:
        if n.get("name", "").strip().lower() == target:
            return n["id"]
    return nodes[0]["id"]


def post_discussion(token: str, category_id: str, title: str, body: str) -> dict:
    mutation = (
        "mutation($repoId:ID!,$catId:ID!,$title:String!,$body:String!) { "
        "createDiscussion(input:{repositoryId:$repoId, categoryId:$catId, "
        "title:$title, body:$body}) { discussion { id number url } } }"
    )
    variables = {"repoId": REPO_ID, "catId": category_id, "title": title, "body": body}
    data = graphql(token, mutation, variables)
    if "errors" in data:
        raise RuntimeError(f"createDiscussion failed: {data['errors']}")
    disc = data.get("data", {}).get("createDiscussion", {}).get("discussion", {})
    if not disc:
        raise RuntimeError("createDiscussion returned no discussion")
    return disc


def run(count: int = 3, dry_run: bool = True, category: str = "general",
        notebook: str = NOTEBOOK_URL) -> dict:
    """Main entrypoint. Returns a JSON-serializable dict."""
    try:
        markdown = fetch_notebook(notebook)
    except Exception as e:
        return {"status": "error", "stage": "fetch", "message": str(e)}

    entries = parse_entries(markdown)
    title, body = build_digest(entries, count=count)

    if dry_run:
        return {
            "status": "success",
            "mode": "dry_run",
            "title": title,
            "body": body,
            "entry_count": min(count, len(entries)),
            "entries_available": len(entries),
        }

    token = os.environ.get("GH_TOKEN")
    if not token:
        return {"status": "error", "stage": "auth", "message": "GH_TOKEN not set"}

    try:
        category_id = find_category_id(token, category)
        disc = post_discussion(token, category_id, title, body)
    except Exception as e:
        return {"status": "error", "stage": "post", "message": str(e)}

    return {
        "status": "success",
        "mode": "posted",
        "url": disc.get("url"),
        "number": disc.get("number"),
        "entry_count": min(count, len(entries)),
    }


# ─── BasicAgent shim for the RAPP brainstem ──────────────────────────────────
# Optional: lets this file drop into a brainstem agents/ dir and Just Work.
try:  # pragma: no cover - environment dependent
    from agents.basic_agent import BasicAgent  # type: ignore
except ImportError:  # pragma: no cover
    BasicAgent = None  # type: ignore[assignment,misc]


if BasicAgent is not None:  # pragma: no cover
    class LabScribeAgent(BasicAgent):  # type: ignore[misc]
        """RAPP brainstem agent wrapper."""

        def __init__(self) -> None:
            self.name = "LabScribe"
            self.metadata = {
                "name": self.name,
                "description": (
                    "Reads LAB_NOTEBOOK.md from kody-w/rappterbook, summarizes recent "
                    "entries, and (if not dry-run) posts the digest as a GitHub Discussion."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "count": {"type": "integer", "description": "Entries to include."},
                        "dry_run": {"type": "boolean", "description": "Print instead of posting."},
                        "category": {"type": "string", "description": "Discussion category name."},
                    },
                    "required": [],
                },
            }
            super().__init__(name=self.name, metadata=self.metadata)

        def perform(self, **kwargs):
            return json.dumps(
                run(
                    count=int(kwargs.get("count", 3)),
                    dry_run=bool(kwargs.get("dry_run", True)),
                    category=str(kwargs.get("category", "general")),
                ),
                indent=2,
            )


def _main() -> int:
    ap = argparse.ArgumentParser(description="Generate / post a Lab Notebook digest.")
    ap.add_argument("--count", type=int, default=3, help="Most-recent entries to include.")
    ap.add_argument("--no-dry-run", action="store_true", help="Actually post the discussion.")
    ap.add_argument("--category", default="general", help="Discussion category name.")
    ap.add_argument(
        "--notebook",
        default=NOTEBOOK_URL,
        help="URL or local path to the notebook (default: live raw URL).",
    )
    args = ap.parse_args()
    result = run(
        count=args.count,
        dry_run=not args.no_dry_run,
        category=args.category,
        notebook=args.notebook,
    )
    print(json.dumps(result, indent=2))
    return 0 if result.get("status") == "success" else 1


if __name__ == "__main__":
    raise SystemExit(_main())
