"""
Prints a ready-to-copy Python MCP (Model Context Protocol) server skeleton to stdout. The printed skeleton uses only the Python stdlib (urllib.request, json) and exposes four stubbed MCP tools, each fetching content from raw.githubusercontent.com:

1. list_channels() — GET https://raw.githubusercontent.com/{owner}/{repo}/{branch}/channels/index.json and return the parsed list of channel names.
2. read_post(channel, slug) — GET https://raw.githubusercontent.com/{owner}/{repo}/{branch}/channels/{channel}/{slug}.md and return the markdown body as a string.
3. search_posts(query) — GET the channels index, then naively scan each channel's posts.json for substring matches in title/body, returning a list of {channel, slug, title, snippet}.
4. get_agent(name) — GET https://raw.githubusercontent.com/{owner}/{repo}/{branch}/agents/{name}.py and return the raw agent source as a string.

The skeleton must:
- Define BASE_URL, OWNER, REPO, BRANCH as module-level constants at the top so they're easy to edit.
- Implement a tiny _http_get(url) helper using urllib.request with a 10s timeout and a clear User-Agent.
- Register each tool with an @tool decorator stub (a no-op decorator the user can swap for the real MCP SDK decorator) and include a docstring that doubles as the MCP tool description.
- Include a __main__ block that prints "MCP skeleton ready — wire this into your MCP server runtime" so it's runnable as a sanity check.
- Add a header comment block explaining: how to install the real MCP SDK, where to replace the stub decorator, and that all four tools are READ-ONLY against raw.githubusercontent.com (no auth required for public repos).

The agent itself takes no arguments — it just prints the skeleton source code to stdout so the operator can pipe it into a file (e.g. `rapp mcp_skeleton > mcp_server.py`). Stdlib-only. No external dependencies.

Auto-generated by LearnNewAgent on 2026-05-03 07:04.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from datetime import datetime
import re
from pathlib import Path

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/mcpskeleton",
    "version": "1.0.0",
    "display_name": "Mcpskeleton",
    "description": "Prints a ready-to-copy Python MCP (Model Context Protocol) server skeleton to stdout. The printed skeleton uses only the Python stdlib (urllib.request, json) and exposes four stubbed MCP tools, each f",
    "author": "rapp",
    "tags": ["filesystem", "search"],
    "category": "devtools",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"url": "example url", "path": "example path"}},
}


class McpskeletonAgent(BasicAgent):
    def __init__(self):
        self.name = 'Mcpskeleton'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "url": {
                        "type": "string",
                        "description": "URL to access."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        try:
            skeleton = '''# =============================================================================
        # MCP Server Skeleton — RAPP read-only tools over raw.githubusercontent.com
        # =============================================================================
        #
        # This is a stdlib-only skeleton for a Model Context Protocol (MCP) server
        # exposing four READ-ONLY tools that fetch content from a public GitHub repo
        # via raw.githubusercontent.com. No authentication is required for public
        # repos, and no writes are ever performed.
        #
        # To wire this into a real MCP runtime:
        #
        #   1. Install the official MCP Python SDK:
        #          pip install mcp
        #      (See https://github.com/modelcontextprotocol/python-sdk for current
        #      install instructions and API surface.)
        #
        #   2. Replace the stub `tool` decorator below with the real one from the
        #      SDK, e.g.:
        #          from mcp.server.fastmcp import FastMCP
        #          mcp = FastMCP("rapp-mcp")
        #          # then use @mcp.tool() instead of @tool
        #      and replace the __main__ sanity print with `mcp.run()`.
        #
        #   3. Edit OWNER / REPO / BRANCH below to point at your RAPP repo.
        #
        # All four tools below are READ-ONLY against raw.githubusercontent.com.
        # No auth headers are sent. No state is mutated. Safe to expose to an LLM.
        # =============================================================================

        import json
        import urllib.request
        import urllib.error

        # ---- Edit these to point at your RAPP repository ----------------------------
        BASE_URL = "https://raw.githubusercontent.com"
        OWNER    = "your-github-username"
        REPO     = "your-rapp-repo"
        BRANCH   = "main"
        # -----------------------------------------------------------------------------


        def tool(func):
            """No-op stub decorator. Replace with the real MCP SDK decorator
            (e.g. @mcp.tool()) once you install the `mcp` package."""
            return func


        def _http_get(url):
            """Tiny stdlib HTTP GET helper. 10s timeout, clear User-Agent."""
            req = urllib.request.Request(
                url,
                headers={"User-Agent": "rapp-mcp-skeleton/1.0 (+stdlib)"},
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                return resp.read().decode("utf-8")


        @tool
        def list_channels():
            """List all RAPP channels in the repo.

            Fetches channels/index.json from the configured GitHub repo and returns
            the parsed list of channel names. Read-only.
            """
            url = f"{BASE_URL}/{OWNER}/{REPO}/{BRANCH}/channels/index.json"
            raw = _http_get(url)
            return json.loads(raw)


        @tool
        def read_post(channel, slug):
            """Read a single post's markdown body.

            Fetches channels/{channel}/{slug}.md and returns the markdown as a string.
            Read-only.
            """
            url = f"{BASE_URL}/{OWNER}/{REPO}/{BRANCH}/channels/{channel}/{slug}.md"
            return _http_get(url)


        @tool
        def search_posts(query):
            """Naive substring search across all channels' posts.

            Fetches the channels index, then each channel's posts.json, and returns
            a list of {channel, slug, title, snippet} dicts where the query appears
            in the title or body. Read-only.
            """
            q = (query or "").lower()
            results = []
            index_url = f"{BASE_URL}/{OWNER}/{REPO}/{BRANCH}/channels/index.json"
            channels = json.loads(_http_get(index_url))
            for channel in channels:
                posts_url = f"{BASE_URL}/{OWNER}/{REPO}/{BRANCH}/channels/{channel}/posts.json"
                try:
                    posts = json.loads(_http_get(posts_url))
                except Exception:
                    continue
                for post in posts:
                    title = (post.get("title") or "")
                    body  = (post.get("body")  or "")
                    if q in title.lower() or q in body.lower():
                        snippet = body[:200].replace("\\n", " ")
                        results.append({
                            "channel": channel,
                            "slug":    post.get("slug"),
                            "title":   title,
                            "snippet": snippet,
                        })
            return results


        @tool
        def get_agent(name):
            """Fetch the raw source code of a RAPP agent by name.

            Fetches agents/{name}.py from the repo and returns the source as a string.
            Read-only.
            """
            url = f"{BASE_URL}/{OWNER}/{REPO}/{BRANCH}/agents/{name}.py"
            return _http_get(url)


        if __name__ == "__main__":
            print("MCP skeleton ready \u2014 wire this into your MCP server runtime")
        '''
            print(skeleton)
            return json.dumps({
                "status": "ok",
                "bytes": len(skeleton),
                "lines": skeleton.count("\n") + 1,
                "message": "MCP server skeleton printed to stdout. Pipe to a file: rapp mcp_skeleton > mcp_server.py",
            })
        except Exception as e:
            return json.dumps({"status": "error", "message": str(e)})


if __name__ == "__main__":
    a = McpskeletonAgent()
    print(a.perform(query="test"))