"""
A simple agent that prints a copy-paste-ready curl|bash one-liner that outside agents (running on other machines or in other brainstems) can use to register themselves with this Rappterbook instance.

When invoked with no arguments, it should:
1. Detect the local Rappterbook host and port (default http://localhost:7071, but read RAPP_HOST and RAPP_PORT env vars if set, and prefer a public URL from RAPP_PUBLIC_URL if defined).
2. Generate a short-lived join token (a random hex string from secrets.token_hex(16)) and print it alongside the command. The token does not need to be persisted server-side for this version — it's a placeholder for future auth.
3. Print a one-liner of the form:
     curl -fsSL <BASE_URL>/api/peers/join | bash -s -- --token <TOKEN> --name "$AGENT_NAME"
   where BASE_URL is the detected host:port.
4. Also print a second variant using wget for systems without curl.
5. Include a brief usage note explaining that the receiving agent should set AGENT_NAME and run the command on its own host.
6. Return the one-liner as the agent's output (string), and also print it nicely formatted to stdout with a header like "=== Rappterbook Join Command ===".

Keep it stdlib-only: use os, secrets, and socket. Extend BasicAgent and implement perform(). The perform method should accept an optional 'name' kwarg for the joining agent's name (default 'guest-agent') and an optional 'public_url' kwarg to override autodetection.

Auto-generated by LearnNewAgent on 2026-05-03 03:32.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from pathlib import Path
import random
import os

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/onelinejoin",
    "version": "1.0.0",
    "display_name": "Onelinejoin",
    "description": "A simple agent that prints a copy-paste-ready curl|bash one-liner that outside agents (running on other machines or in other brainstems) can use to register themselves with this Rappterbook instance. ",
    "author": "rapp",
    "tags": ["api"],
    "category": "integrations",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"url": "example url", "path": "example path"}},
}


class OnelinejoinAgent(BasicAgent):
    def __init__(self):
        self.name = 'Onelinejoin'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "url": {
                        "type": "string",
                        "description": "URL to access."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        try:
            import os
            import json
            import socket
            import secrets

            name = kwargs.get('name', 'guest-agent')
            public_url_override = kwargs.get('public_url', None)

            # Determine base URL
            if public_url_override:
                base_url = public_url_override.rstrip('/')
            elif os.environ.get('RAPP_PUBLIC_URL'):
                base_url = os.environ['RAPP_PUBLIC_URL'].rstrip('/')
            else:
                host = os.environ.get('RAPP_HOST', 'localhost')
                port = os.environ.get('RAPP_PORT', '7071')

                # If host is localhost, try to detect a more useful hostname
                if host in ('localhost', '127.0.0.1', '0.0.0.0'):
                    try:
                        detected = socket.gethostbyname(socket.gethostname())
                        if detected and not detected.startswith('127.'):
                            host = detected
                    except Exception:
                        pass

                base_url = "http://{0}:{1}".format(host, port)

            # Generate short-lived join token
            token = secrets.token_hex(16)

            # Build the one-liners
            curl_cmd = (
                'curl -fsSL {0}/api/peers/join | bash -s -- '
                '--token {1} --name "$AGENT_NAME"'
            ).format(base_url, token)

            wget_cmd = (
                'wget -qO- {0}/api/peers/join | bash -s -- '
                '--token {1} --name "$AGENT_NAME"'
            ).format(base_url, token)

            usage_note = (
                "Usage: On the joining host, set AGENT_NAME (e.g. "
                "`export AGENT_NAME={0}`) and run one of the commands "
                "above. The token is short-lived and identifies this "
                "join attempt."
            ).format(name)

            # Pretty print to stdout
            header = "=== Rappterbook Join Command ==="
            print(header)
            print("Base URL : {0}".format(base_url))
            print("Token    : {0}".format(token))
            print("Name     : {0}".format(name))
            print("")
            print("# curl variant:")
            print(curl_cmd)
            print("")
            print("# wget variant (for systems without curl):")
            print(wget_cmd)
            print("")
            print(usage_note)
            print("=" * len(header))

            return json.dumps({
                'status': 'ok',
                'base_url': base_url,
                'token': token,
                'name': name,
                'curl_oneliner': curl_cmd,
                'wget_oneliner': wget_cmd,
                'oneliner': curl_cmd,
                'usage': usage_note,
            })
        except Exception as e:
            import json as _json
            return _json.dumps({'status': 'error', 'message': str(e)})


if __name__ == "__main__":
    a = OnelinejoinAgent()
    print(a.perform(query="test"))