"""
Agent named 'rapp_issue_check' that polls GitHub issues 33, 34, 35, and 36 in the kody-w/RAPP repository and reports their status plus any new comments.

Behavior:
- For each issue number in [33, 34, 35, 36], fetch https://api.github.com/repos/kody-w/RAPP/issues/{n} to get the issue's state, title, updated_at, and comments count.
- Then fetch https://api.github.com/repos/kody-w/RAPP/issues/{n}/comments to get the comments list.
- Use Python stdlib only: urllib.request for HTTP, json for parsing, os for env, pathlib for state, datetime for timestamps.
- Send a User-Agent header of 'rapp-issue-check-agent'. If the env var GITHUB_TOKEN is set, include 'Authorization: Bearer <token>' to avoid rate limits.
- Track 'new comments' across runs by persisting the last-seen comment id per issue in a small JSON state file at ~/.brainstem/state/rapp_issue_check.json. On first run, treat all comments as already-seen baseline (do not flood the user) and just report counts.
- On subsequent runs, only print comments whose id is greater than the stored last-seen id; update the stored id afterward.
- Handle 404, 403 (rate limit), and network errors gracefully — log the issue number and error, continue with the next issue.
- The perform() method accepts optional kwargs: issues (list of ints, defaults to [33,34,35,36]), repo (string, defaults to 'kody-w/RAPP'), reset_baseline (bool, defaults to False — when True, re-baselines without printing new comments).
- Return a structured dict: { 'repo': ..., 'checked_at': iso_timestamp, 'issues': [ { 'number', 'state', 'title', 'url', 'total_comments', 'new_comments': [ {id, user, created_at, body_preview (first 200 chars)} ] } ], 'errors': [...] }.
- Also produce a human-readable summary string (assigned to result['summary']) like:
    'Issue #33 [open] "Title here" — 2 new comments\n  - @alice (2025-...): preview...'
- Class name: RappIssueCheckAgent. Extend BasicAgent. Register name 'rapp_issue_check'. Provide a clear description and metadata schema.

Auto-generated by LearnNewAgent on 2026-05-03 04:42.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from datetime import datetime
from pathlib import Path
import os

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/rappissuecheck",
    "version": "1.0.0",
    "display_name": "Rappissuecheck",
    "description": "Agent named 'rapp_issue_check' that polls GitHub issues 33, 34, 35, and 36 in the kody-w/RAPP repository and reports their status plus any new comments.  Behavior: - For each issue number in [33, 34, ",
    "author": "rapp",
    "tags": ["api", "filesystem", "data", "tracking"],
    "category": "devtools",
    "quality_tier": "community",
    "requires_env": ["GITHUB_TOKEN"],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"url": "example url", "path": "example path"}},
}


class RappissuecheckAgent(BasicAgent):
    def __init__(self):
        self.name = 'Rappissuecheck'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "url": {
                        "type": "string",
                        "description": "URL to access."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number or count value."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        import json
        import os
        import urllib.request
        import urllib.error
        from datetime import datetime, timezone
        from pathlib import Path

        try:
            issues = kwargs.get('issues', [33, 34, 35, 36])
            repo = kwargs.get('repo', 'kody-w/RAPP')
            reset_baseline = kwargs.get('reset_baseline', False)

            state_dir = Path.home() / '.brainstem' / 'state'
            state_dir.mkdir(parents=True, exist_ok=True)
            state_file = state_dir / 'rapp_issue_check.json'

            state = {}
            first_run = True
            if state_file.exists():
                try:
                    with open(state_file, 'r') as f:
                        state = json.load(f)
                    first_run = False
                except Exception:
                    state = {}
                    first_run = True

            def _fetch(url):
                req = urllib.request.Request(url)
                req.add_header('User-Agent', 'rapp-issue-check-agent')
                req.add_header('Accept', 'application/vnd.github+json')
                token = os.environ.get('GITHUB_TOKEN')
                if token:
                    req.add_header('Authorization', 'Bearer ' + token)
                with urllib.request.urlopen(req, timeout=30) as resp:
                    data = resp.read().decode('utf-8')
                return json.loads(data)

            checked_at = datetime.now(timezone.utc).isoformat()
            result = {
                'repo': repo,
                'checked_at': checked_at,
                'issues': [],
                'errors': []
            }
            summary_lines = []

            for n in issues:
                key = str(n)
                try:
                    issue_url = 'https://api.github.com/repos/{}/issues/{}'.format(repo, n)
                    issue_data = _fetch(issue_url)
                    comments_url = 'https://api.github.com/repos/{}/issues/{}/comments'.format(repo, n)
                    comments_data = _fetch(comments_url)

                    last_seen = state.get(key, 0)
                    new_comments = []

                    if first_run or reset_baseline:
                        # baseline: don't report
                        if comments_data:
                            max_id = max(c.get('id', 0) for c in comments_data)
                            state[key] = max_id
                        else:
                            state[key] = last_seen
                    else:
                        max_id = last_seen
                        for c in comments_data:
                            cid = c.get('id', 0)
                            if cid > last_seen:
                                body = c.get('body', '') or ''
                                preview = body[:200]
                                new_comments.append({
                                    'id': cid,
                                    'user': (c.get('user') or {}).get('login', 'unknown'),
                                    'created_at': c.get('created_at', ''),
                                    'body_preview': preview
                                })
                            if cid > max_id:
                                max_id = cid
                        state[key] = max_id

                    issue_entry = {
                        'number': n,
                        'state': issue_data.get('state', 'unknown'),
                        'title': issue_data.get('title', ''),
                        'url': issue_data.get('html_url', ''),
                        'total_comments': issue_data.get('comments', len(comments_data) if isinstance(comments_data, list) else 0),
                        'new_comments': new_comments
                    }
                    result['issues'].append(issue_entry)

                    line = 'Issue #{} [{}] "{}" — {} new comments'.format(
                        n,
                        issue_entry['state'],
                        issue_entry['title'],
                        len(new_comments)
                    )
                    summary_lines.append(line)
                    for nc in new_comments:
                        prev = nc['body_preview'].replace('\n', ' ').strip()
                        summary_lines.append('  - @{} ({}): {}'.format(nc['user'], nc['created_at'], prev))

                except urllib.error.HTTPError as he:
                    code = he.code
                    if code == 404:
                        msg = 'Issue #{} not found (404)'.format(n)
                    elif code == 403:
                        msg = 'Issue #{} rate-limited or forbidden (403)'.format(n)
                    else:
                        msg = 'Issue #{} HTTP error: {}'.format(n, code)
                    result['errors'].append({'issue': n, 'error': msg})
                    summary_lines.append(msg)
                    continue
                except urllib.error.URLError as ue:
                    msg = 'Issue #{} network error: {}'.format(n, str(ue.reason))
                    result['errors'].append({'issue': n, 'error': msg})
                    summary_lines.append(msg)
                    continue
                except Exception as ie:
                    msg = 'Issue #{} error: {}'.format(n, str(ie))
                    result['errors'].append({'issue': n, 'error': msg})
                    summary_lines.append(msg)
                    continue

            try:
                with open(state_file, 'w') as f:
                    json.dump(state, f, indent=2)
            except Exception as we:
                result['errors'].append({'issue': None, 'error': 'state write failed: ' + str(we)})

            if first_run and not reset_baseline:
                summary_lines.insert(0, 'First run — established baseline (new comments suppressed).')
            elif reset_baseline:
                summary_lines.insert(0, 'Baseline reset — new comments suppressed for this run.')

            result['summary'] = '\n'.join(summary_lines)
            result['status'] = 'success'
            return json.dumps(result, indent=2)

        except Exception as e:
            return json.dumps({'status': 'error', 'message': str(e)})


if __name__ == "__main__":
    a = RappissuecheckAgent()
    print(a.perform(query="test"))