"""
Calls the local claude CLI as a fully separate session via subprocess (claude --print PROMPT). The brainstem server has a minimal PATH so the agent must probe absolute paths (~/.local/bin/claude, /usr/local/bin/claude, /opt/homebrew/bin/claude) and augment subprocess env PATH with those dirs prepended. Reads kwargs["prompt"] (required) and optional kwargs["timeout"] defaulting to 240. Returns JSON with status (ok or error) and either text (stdout, stripped) or message (error reason). Raises no fake-llm fallbacks — if the binary is missing, return status error with an explicit message. Used to fetch a reference response in the rappterbook content bakeoff.

Auto-generated by LearnNewAgent on 2026-05-03 21:13.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from datetime import datetime
from pathlib import Path

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/claude_cli_call",
    "version": "1.0.0",
    "display_name": "ClaudeCliCall",
    "description": "Calls the local claude CLI as a fully separate session via subprocess (claude --print PROMPT). The brainstem server has a minimal PATH so the agent must probe absolute paths (~/.local/bin/claude, /usr",
    "author": "rapp",
    "tags": ["custom"],
    "category": "general",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"path": "example path"}},
}


class ClaudeCliCallAgent(BasicAgent):
    def __init__(self):
        self.name = 'ClaudeCliCall'
        self.metadata = {
            "name": self.name,
            "description": (
                "Call the local claude CLI as a fully separate session "
                "(claude --print PROMPT). Returns JSON with status + text. "
                "Used to fetch a reference response in content bakeoffs."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "The full prompt to send to claude --print."
                    },
                    "timeout": {
                        "type": "integer",
                        "description": "Seconds before subprocess timeout. Default 240."
                    }
                },
                "required": ["prompt"]
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Call claude --print as a fully separate session subprocess."""
        import json, os, subprocess
        # NOTE: parameter is 'prompt' (set in metadata, read below).
        prompt = kwargs.get("prompt")
        if not prompt:
            return json.dumps({"status": "error",
                               "message": "missing required kwarg: prompt"})
        try:
            timeout = int(kwargs.get("timeout", 240))
        except (TypeError, ValueError):
            timeout = 240

        candidates = [
            os.path.expanduser("~/.local/bin/claude"),
            "/usr/local/bin/claude",
            "/opt/homebrew/bin/claude",
        ]
        claude_bin = next((c for c in candidates if os.path.exists(c)), None)
        if not claude_bin:
            return json.dumps({"status": "error",
                               "message": "claude CLI not found at any known path"})

        env = os.environ.copy()
        prepend = (os.path.expanduser("~/.local/bin") + os.pathsep
                   + "/usr/local/bin" + os.pathsep + "/opt/homebrew/bin")
        env["PATH"] = prepend + os.pathsep + env.get("PATH", "")

        import time as _time
        last_stderr = ""
        for attempt in range(2):
            try:
                proc = subprocess.run(
                    [claude_bin, "--print", prompt],
                    capture_output=True, text=True, timeout=timeout, env=env,
                )
                text = (proc.stdout or "").strip()
                if text:
                    return json.dumps({
                        "status": "ok",
                        "text": text,
                        "binary": claude_bin,
                        "attempts": attempt + 1,
                    })
                last_stderr = (proc.stderr or "")[:300]
                if attempt == 0:
                    _time.sleep(5)
                    continue
                return json.dumps({
                    "status": "error",
                    "message": f"claude empty stdout after 2 attempts; stderr: {last_stderr}",
                })
            except subprocess.TimeoutExpired:
                return json.dumps({"status": "error",
                                   "message": f"claude --print timed out after {timeout}s"})
            except Exception as e:
                return json.dumps({"status": "error", "message": str(e)})


if __name__ == "__main__":
    a = ClaudeCliCallAgent()
    print(a.perform(prompt="Say hi in 5 words."))
