"""
Pops the next bakeoff writing task from ~/.brainstem/state/scribe_tasks.json (a JSON object with key "tasks" containing a list of strings). Removes the first item, rewrites the file, returns JSON with the popped task. If the file is missing or empty, returns a built-in fallback task targeting c/philosophy on rappterbook. Used at the start of every scribe round.

Auto-generated by LearnNewAgent on 2026-05-03 21:02.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
from pathlib import Path

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/pop_scribe_task",
    "version": "1.0.0",
    "display_name": "PopScribeTask",
    "description": "Pops the next bakeoff writing task from ~/.brainstem/state/scribe_tasks.json (a JSON object with key \"tasks\" containing a list of strings). Removes the first item, rewrites the file, returns JSON wi",
    "author": "rapp",
    "tags": ["filesystem"],
    "category": "general",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"path": "example path"}},
}


class PopScribeTaskAgent(BasicAgent):
    def __init__(self):
        self.name = 'PopScribeTask'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Pop the next bakeoff writing task from ~/.brainstem/state/scribe_tasks.json."""
        import json, os
        from pathlib import Path
        tasks_path = Path.home() / ".brainstem" / "state" / "scribe_tasks.json"
        fallback = {
            "community": "philosophy",
            "instance": "rappterbook",
            "prompt": (
                "Write a thoughtful 180-260 word [REFLECTION] post for "
                "c/philosophy on rappterbook. Cite at least one platform "
                "mechanism by name. No marketing voice. No 'Hot take:' lede."
            ),
            "source": "fallback",
        }
        try:
            if not tasks_path.exists():
                return json.dumps({"status": "ok", "task": fallback,
                                   "remaining": 0,
                                   "note": "tasks file missing; using fallback"})
            with open(tasks_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            tasks = data.get("tasks", []) if isinstance(data, dict) else []
            if not tasks:
                return json.dumps({"status": "ok", "task": fallback,
                                   "remaining": 0,
                                   "note": "tasks file empty; using fallback"})
            popped = tasks[0]
            data["tasks"] = tasks[1:]
            tmp_path = tasks_path.with_suffix(".json.tmp")
            with open(tmp_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)
            os.replace(str(tmp_path), str(tasks_path))
            return json.dumps({"status": "ok", "task": popped,
                               "remaining": len(data["tasks"]),
                               "source": "queue"})
        except Exception as e:
            return json.dumps({"status": "error", "message": str(e)})


if __name__ == "__main__":
    a = PopScribeTaskAgent()
    print(a.perform())
