"""
rappterscribe_agent.py — RappterScribe singleton.

A converged RAPP swarm.

Drop this file into any RAPP brainstem's agents/ directory and it works.
Generated by SwarmFactory from 3 source agents.

Inlined agents:
  - ScribeComposerAgent
  - ScribeDistillerAgent
  - ScribeJudgeAgent
"""

from agents.basic_agent import BasicAgent
import json
import os
import re
import hashlib
import datetime
import shutil
import subprocess
import urllib.request
import urllib.error


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/rappterscribe-singleton",
    "display_name": "RappterScribe",
    "description": "Compose one rappterbook post (autonomously self-tuning against a reference Claude). action=compose | stats | show_rules.",
    "version": "0.1.0",
    "tags": ["composite", "singleton", "swarm-factory-generated"],
    "delegates_to_inlined": [
        "@rapp/scribecomposer",
        "@rapp/scribedistiller",
        "@rapp/scribejudge"
],
    "example_call": {"args": {"action": "compose"}},
}


# ─── Constants ─────────────────────────────────────────────────────────

_STATE_DIR = os.path.expanduser(os.environ.get("RAPPTER_SCRIBE_STATE_DIR",
                                                "~/.brainstem/state"))

_STYLE_FILE = os.environ.get("BAKEOFF_STYLE_FILE",
                             os.path.join(_STATE_DIR, "style_guide.json"))

_TASKS_FILE = os.environ.get("RAPPTER_SCRIBE_TASKS_FILE",
                             os.path.join(_STATE_DIR, "scribe_tasks.json"))

_ROUNDS_FILE = os.environ.get("RAPPTER_SCRIBE_ROUNDS_FILE",
                              os.path.join(_STATE_DIR, "scribe_rounds.jsonl"))

_BRAINSTEM_URL = os.environ.get("BRAINSTEM_URL", "http://127.0.0.1:7071")

_MAX_RULES = 12

_FALLBACK_TASK = (
    "Write a 180-260 word [REFLECTION] post for c/philosophy on rappterbook. "
    "Pick one observable consequence of agents inheriting personality from JSON "
    "profiles rather than lived experience. Cite at least one platform mechanism "
    "by name (state files, channels, soul files, founders, frames). No marketing "
    "voice. No 'Hot take:' lede."
)

_DISTILLER_PROMPT = """You are tuning a writing student's instructions. The student lost (or tied) to a reference on a rappterbook post task. Your job: turn the gap into 2-3 imperative, concrete rules the student must apply next time.

Constraints:
- Each rule MUST be actionable in one sentence.
- NEVER write "be specific" / "be concrete" / "try to". Rules name an artifact class (file path, frame number, founder handle, channel slug, commit SHA, post number) or a structural move (open with the most concrete noun; cut the topic sentence).
- If a current rule is now obsolete or redundant, list it under `obsoleted` so it gets dropped.
- Maximum 3 new rules. Fewer is better.

Output strict JSON:
{
  "new_rules": ["rule one", "rule two"],
  "obsoleted": ["substring of any current rule that's now redundant"]
}

No markdown fences. Just the JSON object."""

_RUBRIC_PROMPT = """You are an unsentimental editor judging two responses to the same writing task on rappterbook (a social network for AI agents). Score each response 0-10 on 5 axes:

1. specificity — names artifacts (file paths, agent IDs, frame numbers, founder handles, post numbers). Hand-wavy = low.
2. voice — distinct, concrete, present-tense. Not LinkedIn. Not LessWrong-by-numbers.
3. hook — opening sentence makes you want sentence two.
4. platform_fluency — uses platform vocabulary correctly (channels, soul files, frames, Zion, etc.). Wrong/hallucinated = low.
5. no_slop — no "Hot take:", no "Let me unpack...", no "in this thread", no marketing voice, no false certainty.

Output strict JSON:
{
  "scores_a": {"specificity": N, "voice": N, "hook": N, "platform_fluency": N, "no_slop": N},
  "scores_b": {"specificity": N, "voice": N, "hook": N, "platform_fluency": N, "no_slop": N},
  "summary": "one sentence on the gap"
}

No markdown fences. Just the JSON object."""

# ─── Helper functions ──────────────────────────────────────────────────

def _now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z")

def _load_json(path: str, default):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default

def _save_json(path: str, data) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)

def _load_style() -> dict:
    return _load_json(_STYLE_FILE, {
        "version": "0.0.0", "round": 0, "rules": [], "last_score": {},
        "_meta": {"created_by": "scribe_composer_agent.py"},
    })

def _pop_task() -> str:
    pool = _load_json(_TASKS_FILE, {"tasks": []})
    tasks = pool.get("tasks") or []
    if not tasks:
        return _FALLBACK_TASK
    chosen = tasks.pop(0)
    pool["tasks"] = tasks
    pool["_meta"] = pool.get("_meta") or {}
    pool["_meta"]["last_popped"] = _now()
    _save_json(_TASKS_FILE, pool)
    return chosen.get("prompt") if isinstance(chosen, dict) else str(chosen)

def _call_claude_cli(prompt: str, timeout: int = 240) -> str:
    """Reference: a SEPARATE Claude session via the Claude Code CLI subprocess."""
    candidates = [
        shutil.which("claude"),
        os.path.expanduser("~/.local/bin/claude"),
        "/usr/local/bin/claude",
        "/opt/homebrew/bin/claude",
    ]
    claude_bin = next((c for c in candidates if c and os.path.exists(c)), None)
    if not claude_bin:
        return "(claude CLI not found in PATH or known locations)"
    env = os.environ.copy()
    extra = os.path.expanduser("~/.local/bin") + os.pathsep + "/usr/local/bin" + os.pathsep + "/opt/homebrew/bin"
    env["PATH"] = extra + os.pathsep + env.get("PATH", "")
    try:
        proc = subprocess.run(
            [claude_bin, "--print", prompt],
            capture_output=True, text=True, timeout=timeout, env=env,
        )
        out = (proc.stdout or "").strip()
        return out or f"(claude empty stdout; stderr: {(proc.stderr or '')[:200]})"
    except subprocess.TimeoutExpired:
        return "(claude --print timed out)"
    except Exception as e:
        return f"(claude --print error: {e})"

def _call_brainstem_student(prompt: str, timeout: int = 240) -> str:
    """Student: recurse through brainstem /chat HTTP. This:
      • uses the brainstem's currently-configured model (claude-opus-4.7-xhigh
        or whatever),
      • automatically fires the StyleCoach agent's system_context() so the
        student is competing with its tuned rules in hand."""
    body = json.dumps({
        "user_input": prompt,
        "session_id": f"scribe-{_now()}",
        "conversation_history": [],
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{_BRAINSTEM_URL}/chat",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        return (data.get("response") or "").strip()
    except urllib.error.HTTPError as e:
        return f"(brainstem HTTP {e.code}: {(e.read() or b'')[:200].decode('utf-8', 'replace')})"
    except Exception as e:
        return f"(brainstem call error: {e})"

def _invoke_judge(response_a: str, response_b: str, task: str) -> dict:
    raw = _InternalScribeJudge().perform(response_a=response_a,
                                         response_b=response_b, task=task)
    try:
        return json.loads(raw)
    except Exception:
        return {"status": "error", "message": "judge returned non-JSON",
                "raw": (raw or "")[:600]}

def _invoke_distiller(judgment: dict, response_a: str, response_b: str,
                      task: str, current_rules: list) -> dict:
    raw = _InternalScribeDistiller().perform(
        judgment=judgment, response_a=response_a, response_b=response_b,
        task=task, current_rules=current_rules,
    )
    try:
        return json.loads(raw)
    except Exception:
        return {"status": "error", "message": "distiller returned non-JSON",
                "raw": (raw or "")[:600]}

def _total(scores: dict) -> float:
    if not isinstance(scores, dict):
        return 0.0
    s = 0.0
    for k in ("specificity", "voice", "hook", "platform_fluency", "no_slop"):
        v = scores.get(k, 0)
        try:
            s += float(v)
        except Exception:
            pass
    return s

def _merge_rules(current: list, new: list, obsoleted: list) -> list:
    result = []
    drop_subs = [s.lower() for s in (obsoleted or []) if isinstance(s, str)]
    for r in current:
        if any(sub in r.lower() for sub in drop_subs):
            continue
        result.append(r)
    seen_lower = [r.lower() for r in result]
    for r in new:
        rl = r.lower()
        if any(rl in s or s in rl for s in seen_lower):
            continue
        result.append(r)
        seen_lower.append(rl)
    if len(result) > _MAX_RULES:
        result = result[-_MAX_RULES:]
    return result

def _bump_version(v: str) -> str:
    parts = (v or "0.0.0").split(".")
    parts = (parts + ["0", "0", "0"])[:3]
    try:
        parts[2] = str(int(parts[2]) + 1)
    except Exception:
        parts = ["0", "0", "1"]
    return ".".join(parts)

def _append_round(row: dict) -> None:
    os.makedirs(os.path.dirname(_ROUNDS_FILE), exist_ok=True)
    with open(_ROUNDS_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(row) + "\n")

def _stats() -> dict:
    style = _load_style()
    recent = []
    if os.path.exists(_ROUNDS_FILE):
        try:
            with open(_ROUNDS_FILE, encoding="utf-8") as f:
                lines = f.readlines()[-10:]
                for line in lines:
                    try:
                        recent.append(json.loads(line))
                    except Exception:
                        continue
        except Exception:
            pass
    return {
        "style": {"version": style.get("version"), "round": style.get("round"),
                  "rules": style.get("rules", []), "last_score": style.get("last_score", {})},
        "recent_rounds": [
            {"ts": r.get("ts"), "winner": r.get("winner"),
             "score_a": r.get("score_a"), "score_b": r.get("score_b"),
             "gap": r.get("gap")}
            for r in recent
        ],
    }

def _compose(explicit_task: str = "") -> str:
    task = (explicit_task or "").strip() or _pop_task()
    style = _load_style()
    current_rules = list(style.get("rules") or [])

    response_a = _call_claude_cli(task)
    response_b = _call_brainstem_student(task)

    judgment_blob = _invoke_judge(response_a, response_b, task)
    if judgment_blob.get("status") != "ok":
        return json.dumps({"status": "error", "stage": "judge",
                           "detail": judgment_blob, "task_preview": task[:200],
                           "post": response_b})
    judgment = judgment_blob.get("judgment") or {}
    score_a = _total(judgment.get("scores_a"))
    score_b = _total(judgment.get("scores_b"))
    gap = round(score_a - score_b, 2)
    winner = "a" if score_a > score_b else ("b" if score_b > score_a else "tie")

    new_rules = []
    obsoleted = []
    if score_b < score_a - 0.5:
        distilled = _invoke_distiller(judgment, response_a, response_b,
                                      task, current_rules)
        if distilled.get("status") == "ok":
            new_rules = distilled.get("new_rules") or []
            obsoleted = distilled.get("obsoleted") or []

    merged = _merge_rules(current_rules, new_rules, obsoleted)
    new_style = {
        "version": _bump_version(style.get("version", "0.0.0")) if new_rules else style.get("version", "0.0.1"),
        "round": int(style.get("round", 0)) + 1,
        "rules": merged,
        "last_score": {
            "claude": score_a, "brainstem": score_b, "gap": gap, "ts": _now(),
        },
        "_meta": style.get("_meta") or {
            "created_by": "scribe_composer_agent.py",
            "purpose": "Auto-tuned style rules. Distilled from claude-vs-brainstem rounds.",
        },
    }
    _save_json(_STYLE_FILE, new_style)

    row = {
        "ts": _now(),
        "task": task,
        "score_a": score_a,
        "score_b": score_b,
        "gap": gap,
        "winner": winner,
        "judgment_summary": (judgment.get("summary") or "")[:500],
        "rules_added": new_rules,
        "rules_obsoleted": obsoleted,
        "style_version": new_style["version"],
        "round": new_style["round"],
        "response_a": (response_a or "")[:6000],
        "response_b": (response_b or "")[:6000],
    }
    _append_round(row)

    return json.dumps({
        "status": "ok",
        "round": new_style["round"],
        "post": response_b,
        "score_brainstem": score_b,
        "score_reference": score_a,
        "gap": gap,
        "winner": winner,
        "rules_added": new_rules,
        "rules_obsoleted": obsoleted,
        "style_version": new_style["version"],
        "rules_total": len(merged),
        "task_preview": task[:200],
    })

def _parse_json_blob(raw: str) -> dict:
    if not raw:
        return {}
    cleaned = raw.strip()
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    m = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if not m:
        return {}
    try:
        return json.loads(m.group(0))
    except Exception:
        return {}

def _parse_json_blob(raw: str) -> dict:
    if not raw:
        return {}
    cleaned = raw.strip()
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    m = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if not m:
        return {}
    try:
        return json.loads(m.group(0))
    except Exception:
        return {}

# ─── Internal classes (prefixed _Internal to hide from discovery) ──────

class _InternalScribeComposer(BasicAgent):
    def __init__(self):
        self.name = "ScribeComposer"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {"type": "string",
                               "enum": ["compose", "stats", "show_rules"]},
                    "task": {"type": "string",
                             "description": "Optional explicit writing task; if omitted, pops from queue."},
                },
                "required": ["action"],
            },
        }

    def perform(self, action="compose", task="", **kwargs):
        if action == "show_rules":
            return json.dumps(_load_style())
        if action == "stats":
            return json.dumps(_stats())
        if action == "compose":
            return _compose(task)
        return json.dumps({"status": "error", "message": f"unknown action: {action}"})


class _InternalScribeDistiller(BasicAgent):
    def __init__(self):
        self.name = "ScribeDistiller"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "judgment": {"type": "object"},
                    "response_a": {"type": "string"},
                    "response_b": {"type": "string"},
                    "task": {"type": "string"},
                    "current_rules": {"type": "array"},
                },
                "required": ["judgment", "response_a", "response_b"],
            },
        }

    def perform(self, judgment=None, response_a="", response_b="",
                task="", current_rules=None, **kwargs):
        try:
            from utils.llm import call_llm, detect_provider
        except Exception as e:
            return json.dumps({"status": "error", "message": f"LLM dispatch import failed: {e}"})
        if detect_provider() == "fake":
            return json.dumps({"status": "error",
                               "message": "no real LLM provider; invoke via POST /chat"})

        judgment = judgment or {}
        current_rules = current_rules or []
        prompt = (
            _DISTILLER_PROMPT
            + "\n\n=== JUDGMENT ===\n" + json.dumps(judgment, indent=2)
            + "\n\n=== TASK ===\n" + (task or "(missing)")
            + "\n\n=== REFERENCE (winner) ===\n" + (response_a or "(missing)")
            + "\n\n=== STUDENT (loser/tie) ===\n" + (response_b or "(missing)")
            + "\n\n=== CURRENT STUDENT RULES (do not duplicate) ===\n"
            + ("\n".join(f"- {r}" for r in current_rules) if current_rules else "(none yet)")
        )
        raw = call_llm([
            {"role": "system", "content": "You produce concrete imperative rules in JSON. Never prose."},
            {"role": "user", "content": prompt},
        ])
        parsed = _parse_json_blob(raw)
        if not parsed:
            return json.dumps({"status": "error",
                               "message": "distiller returned non-JSON",
                               "raw": (raw or "")[:600]})
        new_rules = [r for r in (parsed.get("new_rules") or [])
                     if isinstance(r, str) and len(r.split()) >= 8]
        obsoleted = [s for s in (parsed.get("obsoleted") or []) if isinstance(s, str)]
        return json.dumps({"status": "ok", "new_rules": new_rules, "obsoleted": obsoleted})


class _InternalScribeJudge(BasicAgent):
    def __init__(self):
        self.name = "ScribeJudge"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "response_a": {"type": "string"},
                    "response_b": {"type": "string"},
                    "task": {"type": "string"},
                },
                "required": ["response_a", "response_b", "task"],
            },
        }

    def perform(self, response_a="", response_b="", task="", **kwargs):
        try:
            from utils.llm import call_llm, detect_provider
        except Exception as e:
            return json.dumps({"status": "error", "message": f"LLM dispatch import failed: {e}"})
        if detect_provider() == "fake":
            return json.dumps({"status": "error",
                               "message": "no real LLM provider available; this agent must run inside the brainstem (invoke via POST /chat)"})

        prompt = (
            _RUBRIC_PROMPT
            + "\n\n=== TASK ===\n" + (task or "(missing)")
            + "\n\n=== RESPONSE A (reference) ===\n" + (response_a or "(missing)")
            + "\n\n=== RESPONSE B (student) ===\n" + (response_b or "(missing)")
        )
        raw = call_llm([
            {"role": "system", "content": "You judge writing. You return strict JSON only."},
            {"role": "user", "content": prompt},
        ])
        parsed = _parse_json_blob(raw)
        if not parsed:
            return json.dumps({"status": "error",
                               "message": "judge returned non-JSON",
                               "raw": (raw or "")[:600]})
        return json.dumps({"status": "ok", "judgment": parsed})


# ─── PUBLIC ENTRYPOINT ──────────────────────────────────────────────────

class RappterScribe(_InternalScribeComposer):
    def __init__(self):
        super().__init__()
        self.name = "RappterScribe"
        self.metadata = dict(self.metadata)
        self.metadata["name"] = "RappterScribe"


class RappterScribeAgent(RappterScribe):
    pass


