"""
Honest Dashboard MVP — a single-page HTML dashboard that renders live, factual counts pulled directly from existing brainstem state files. No fabrication, no spin: if a number can't be sourced from disk, it shows as "—". 

Endpoint: GET /api/honest-dashboard returns a self-contained HTML page (inline CSS, vanilla JS, no external deps) suitable for opening in a browser or embedding in an iframe. A second endpoint GET /api/honest-dashboard/data returns the same data as JSON for programmatic consumers; the HTML page polls this every 5 seconds via fetch() to stay live.

Data sources (all read-only, stdlib only):
  1. Brainstems: scan ~/.brainstem/peers/*.json (or BRAINSTEM_PEERS_DIR env). Each file = one known brainstem. Count files, extract 'name' and 'last_seen' fields. If the directory doesn't exist, report 0 and surface the missing path in a 'sources' panel — don't fake it.
  2. Agents: walk ./agents/ relative to the brainstem root, count *_agent.py files (excluding __init__.py and files starting with _). For each, capture mtime as last-modified.
  3. Recent ticks: read ~/.brainstem/ticks.log or ./logs/ticks.log if present, tailing the last 50 lines. Parse each line as 'ISO8601\ttask\tstatus' when possible; otherwise show the raw line. Count ticks in the last 24h and last 1h.
  4. Last-seen timestamps: for each brainstem peer file and the local brainstem itself (mtime of ./soul.md or ./brainstem.py), render as relative time ('3m ago', '2h ago', 'yesterday').

Page layout (single column, max-width 760px, dark theme, monospace headings):
  - Header: 'Honest Dashboard' + subtitle 'Numbers from disk. Nothing else.' + a small 'updated Xs ago' indicator.
  - Four stat cards in a 2x2 grid: Brainstems, Agents, Ticks (24h), Ticks (1h). Each card shows the integer big, source-file path small underneath.
  - Recent ticks table: timestamp | task | status, last 10 rows, newest first.
  - Peers table: name | last seen (relative) | last seen (absolute UTC).
  - Footer: 'Sources' collapsible <details> listing every file path read this cycle with a green check if found, gray dash if missing.

Honesty rules baked in:
  - Never invent counts. Missing source = '—' with a tooltip explaining which file was missing.
  - Show the read timestamp on every card so stale data is obvious.
  - All file reads wrapped in try/except; failures surface in the Sources footer rather than crashing the page.
  - No external CDNs, no tracking, no analytics. Page works fully offline.

The agent's perform() method routes on request path: '/data' suffix returns JSON, anything else returns the HTML page with Content-Type text/html. Implementation uses only os, json, pathlib, datetime, glob from stdlib.

Auto-generated by LearnNewAgent on 2026-05-03 19:24.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from bs4 import BeautifulSoup
from datetime import datetime
from pathlib import Path

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/honestdashboardagent",
    "version": "1.0.0",
    "display_name": "Honestdashboardagent",
    "description": "Honest Dashboard MVP — a single-page HTML dashboard that renders live, factual counts pulled directly from existing brainstem state files. No fabrication, no spin: if a number can't be sourced from di",
    "author": "rapp",
    "tags": ["api", "filesystem", "data", "tracking"],
    "category": "general",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"url": "example url", "path": "example path"}},
}


class HonestdashboardagentAgent(BasicAgent):
    def __init__(self):
        self.name = 'Honestdashboardagent'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "url": {
                        "type": "string",
                        "description": "URL to access."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number or count value."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        (LLM dispatch error: The read operation timed out)


if __name__ == "__main__":
    a = HonestdashboardagentAgent()
    print(a.perform(query="test"))
