"""
Fetches the Rappterbook continuum health stats. Uses urllib.request (stdlib only) to GET https://raw.githubusercontent.com/kody-w/rappterbook/main/state/stats.json, parses the JSON body, and returns a dict containing total_posts and total_agents from that document. On network or parse failure, return {"error": "<reason>", "total_posts": null, "total_agents": null}. Set a 10 second timeout. No external dependencies — Python standard library only (urllib.request, json).

Auto-generated by LearnNewAgent on 2026-05-03 13:37.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from datetime import datetime

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/rappterbookhealth",
    "version": "1.0.0",
    "display_name": "Rappterbookhealth",
    "description": "Fetches the Rappterbook continuum health stats. Uses urllib.request (stdlib only) to GET https://raw.githubusercontent.com/kody-w/rappterbook/main/state/stats.json, parses the JSON body, and returns a",
    "author": "rapp",
    "tags": ["custom"],
    "category": "integrations",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"url": "example url"}},
}


class RappterbookhealthAgent(BasicAgent):
    def __init__(self):
        self.name = 'Rappterbookhealth'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "url": {
                        "type": "string",
                        "description": "URL to access."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        import json
                import urllib.request
                import urllib.error

                url = kwargs.get('url', 'https://raw.githubusercontent.com/kody-w/rappterbook/main/state/stats.json')
                timeout = kwargs.get('timeout', 10)

                try:
                    req = urllib.request.Request(url, headers={'User-Agent': 'RAPP-Brainstem/1.0'})
                    with urllib.request.urlopen(req, timeout=timeout) as resp:
                        raw = resp.read().decode('utf-8')
                    data = json.loads(raw)
                    total_posts = data.get('total_posts')
                    total_agents = data.get('total_agents')
                    return json.dumps({
                        'status': 'success',
                        'total_posts': total_posts,
                        'total_agents': total_agents
                    })
                except urllib.error.HTTPError as e:
                    return json.dumps({
                        'status': 'error',
                        'message': 'HTTP {}: {}'.format(e.code, str(e)),
                        'total_posts': None,
                        'total_agents': None
                    })
                except urllib.error.URLError as e:
                    return json.dumps({
                        'status': 'error',
                        'message': 'URL error: {}'.format(str(e.reason)),
                        'total_posts': None,
                        'total_agents': None
                    })
                except (ValueError, json.JSONDecodeError) as e:
                    return json.dumps({
                        'status': 'error',
                        'message': 'Parse error: {}'.format(str(e)),
                        'total_posts': None,
                        'total_agents': None
                    })
                except Exception as e:
                    return json.dumps({
                        'status': 'error',
                        'message': str(e),
                        'total_posts': None,
                        'total_agents': None
                    })


if __name__ == "__main__":
    a = RappterbookhealthAgent()
    print(a.perform(query="test"))
