"""
An agent that smoke-tests every Rappterbook SDK shipped in this repo against the live raw URL surface. On perform(), it walks two trees:

1. sdk/python/ — for each *.py module that exposes a top-level client class or fetch helper, import it via importlib.util.spec_from_file_location, instantiate with default args, and call its primary "fetch" / "get" / "list" / "raw" method (auto-detected by inspecting public callables in priority order: raw, fetch_raw, get_raw, fetch, get, list, ping, health). Capture the return value, type, byte length if bytes/str, and a short sample (first 200 chars repr).

2. sdk/javascript/ — for each *.js or *.mjs file, run it as a Node subprocess: `node -e "import('FILE').then(m => { const c = m.default || m; const fn = c.fetchRaw || c.fetch || c.get || c.raw || c.list; return Promise.resolve(typeof fn === 'function' ? fn.call(c) : null); }).then(v => console.log(JSON.stringify({ok:true, sample: String(v).slice(0,200), type: typeof v}))).catch(e => console.log(JSON.stringify({ok:false, err: String(e)})))"`. Capture stdout, parse the JSON line, time out after 15 seconds per file using subprocess.run(timeout=15).

For BOTH languages, the test passes only if the call returns non-empty data sourced from the live raw URL (heuristic: response is bytes/str of length > 0, OR an object/dict/list that is non-empty). Network errors, import errors, timeouts, and missing methods all count as failures with a short reason.

Output a structured markdown report with three sections:
- Summary table: SDK name | language | status (✅/❌) | bytes_or_items | reason_if_failed
- Python detail: per-module dict with import_ok, method_called, return_type, sample, error
- JavaScript detail: per-file dict with spawn_ok, parsed_json, sample, stderr_tail, error

Also return a machine-readable dict in the agent's normal return envelope: {"summary": {...counts...}, "python": [...], "javascript": [...], "passed": bool}.

Implementation notes:
- Stdlib only: pathlib, importlib.util, subprocess, json, inspect, time, traceback.
- Resolve the repo root by walking up from __file__ until a directory containing both sdk/python and sdk/javascript is found; fall back to cwd.
- Skip files starting with _ or named __init__.py / index.js when iterating.
- Never raise out of perform(); always return a report even if zero SDKs are found ("no_sdks_discovered": true).
- Include total wall-clock time and per-SDK elapsed_ms.
- Use a 10-second timeout per Python call via signal.alarm on POSIX, or threaded watchdog fallback on Windows.

Auto-generated by LearnNewAgent on 2026-05-03 08:16.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from datetime import datetime
from pathlib import Path

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/sdksmoketest",
    "version": "1.0.0",
    "display_name": "Sdksmoketest",
    "description": "An agent that smoke-tests every Rappterbook SDK shipped in this repo against the live raw URL surface. On perform(), it walks two trees:  1. sdk/python/ — for each *.py module that exposes a top-level",
    "author": "rapp",
    "tags": ["filesystem", "data"],
    "category": "devtools",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"url": "example url", "path": "example path"}},
}


class SdksmoketestAgent(BasicAgent):
    def __init__(self):
        self.name = 'Sdksmoketest'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "url": {
                        "type": "string",
                        "description": "URL to access."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number or count value."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        import json, subprocess, time, traceback, inspect, sys, threading
                import importlib.util
                from pathlib import Path

                t_start = time.time()

                try:
                    # Resolve repo root
                    try:
                        here = Path(__file__).resolve()
                    except NameError:
                        here = Path.cwd().resolve()

                    repo_root = None
                    for candidate in [here] + list(here.parents):
                        try:
                            if (candidate / "sdk" / "python").is_dir() and (candidate / "sdk" / "javascript").is_dir():
                                repo_root = candidate
                                break
                        except Exception:
                            continue
                    if repo_root is None:
                        repo_root = Path.cwd().resolve()

                    py_dir = repo_root / "sdk" / "python"
                    js_dir = repo_root / "sdk" / "javascript"

                    python_results = []
                    javascript_results = []

                    method_priority = ["raw", "fetch_raw", "get_raw", "fetch", "get", "list", "ping", "health"]

                    def _run_with_timeout(fn, timeout_s):
                        """Run fn() with timeout. Returns (ok, result, err)."""
                        result_box = {"ok": False, "result": None, "err": None}
                        def _target():
                            try:
                                result_box["result"] = fn()
                                result_box["ok"] = True
                            except Exception as e:
                                result_box["err"] = f"{type(e).__name__}: {e}"
                                result_box["ok"] = False
                        th = threading.Thread(target=_target, daemon=True)
                        th.start()
                        th.join(timeout_s)
                        if th.is_alive():
                            return (False, None, f"timeout after {timeout_s}s")
                        return (result_box["ok"], result_box["result"], result_box["err"])

                    def _is_nonempty(val):
                        if val is None:
                            return False, 0
                        if isinstance(val, (bytes, bytearray)):
                            return len(val) > 0, len(val)
                        if isinstance(val, str):
                            return len(val) > 0, len(val)
                        if isinstance(val, (list, tuple, dict, set)):
                            return len(val) > 0, len(val)
                        # Other object - treat as non-empty if truthy
                        try:
                            return bool(val), 1
                        except Exception:
                            return True, 1

                    def _sample(val, n=200):
                        try:
                            return repr(val)[:n]
                        except Exception:
                            return "<unrepresentable>"

                    # ---- Python SDKs ----
                    py_files = []
                    if py_dir.is_dir():
                        for p in sorted(py_dir.rglob("*.py")):
                            name = p.name
                            if name.startswith("_") or name == "__init__.py":
                                continue
                            py_files.append(p)

                    for pyf in py_files:
                        sdk_name = pyf.stem
                        t0 = time.time()
                        entry = {
                            "sdk": sdk_name,
                            "path": str(pyf.relative_to(repo_root)),
                            "language": "python",
                            "import_ok": False,
                            "method_called": None,
                            "return_type": None,
                            "sample": None,
                            "bytes_or_items": 0,
                            "passed": False,
                            "error": None,
                            "elapsed_ms": 0,
                        }
                        try:
                            mod_name = f"_rapp_sdk_probe_{sdk_name}_{int(time.time()*1000)}"
                            spec = importlib.util.spec_from_file_location(mod_name, str(pyf))
                            if spec is None or spec.loader is None:
                                raise ImportError("could not build spec")
                            module = importlib.util.module_from_spec(spec)
                            sys.modules[mod_name] = module
                            spec.loader.exec_module(module)
                            entry["import_ok"] = True

                            # Find a target: top-level callable in priority order, or a class with such methods
                            target_callable = None
                            target_method_name = None

                            # First: module-level functions
                            for mname in method_priority:
                                attr = getattr(module, mname, None)
                                if callable(attr) and not inspect.isclass(attr):
                                    target_callable = attr
                                    target_method_name = mname
                                    break

                            # Second: top-level class
                            if target_callable is None:
                                for attr_name in dir(module):
                                    if attr_name.startswith("_"):
                                        continue
                                    attr = getattr(module, attr_name)
                                    if inspect.isclass(attr) and attr.__module__ == module.__name__:
                                        # try instantiate
                                        instance = None
                                        try:
                                            instance = attr()
                                        except Exception:
                                            continue
                                        for mname in method_priority:
                                            m = getattr(instance, mname, None)
                                            if callable(m):
                                                target_callable = m
                                                target_method_name = f"{attr_name}.{mname}"
                                                break
                                        if target_callable is not None:
                                            break

                            if target_callable is None:
                                entry["error"] = "no fetch-style method found"
                            else:
                                entry["method_called"] = target_method_name
                                ok, result, err = _run_with_timeout(lambda: target_callable(), 10)
                                if not ok:
                                    entry["error"] = err or "call failed"
                                else:
                                    entry["return_type"] = type(result).__name__
                                    nonempty, size = _is_nonempty(result)
                                    entry["bytes_or_items"] = size
                                    entry["sample"] = _sample(result, 200)
                                    if nonempty:
                                        entry["passed"] = True
                                    else:
                                        entry["error"] = "empty response"
                        except Exception as e:
                            entry["error"] = f"{type(e).__name__}: {e}"

                        entry["elapsed_ms"] = int((time.time() - t0) * 1000)
                        python_results.append(entry)

                    # ---- JavaScript SDKs ----
                    js_files = []
                    if js_dir.is_dir():
                        for p in sorted(list(js_dir.rglob("*.js")) + list(js_dir.rglob("*.mjs"))):
                            name = p.name
                            if name.startswith("_") or name == "index.js":
                                continue
                            # skip node_modules
                            if "node_modules" in p.parts:
                                continue
                            js_files.append(p)

                    for jsf in js_files:
                        sdk_name = jsf.stem
                        t0 = time.time()
                        entry = {
                            "sdk": sdk_name,
                            "path": str(jsf.relative_to(repo_root)),
                            "language": "javascript",
                            "spawn_ok": False,
                            "parsed_json": None,
                            "sample": None,
                            "bytes_or_items": 0,
                            "passed": False,
                            "stderr_tail": None,
                            "error": None,
                            "elapsed_ms": 0,
                        }
                        try:
                            file_url = jsf.resolve().as_uri()
                            js_code = (
                                "import(" + json.dumps(file_url) + ").then(m => { "
                                "const c = m.default || m; "
                                "const fn = c.fetchRaw || c.fetch || c.get || c.raw || c.list; "
                                "return Promise.resolve(typeof fn === 'function' ? fn.call(c) : null); "
                                "}).then(v => { "
                                "let size = 0; "
                                "if (v == null) size = 0; "
                                "else if (typeof v === 'string') size = v.length; "
                                "else if (Array.isArray(v)) size = v.length; "
                                "else if (typeof v === 'object') size = Object.keys(v).length; "
                                "else size = 1; "
                                "console.log(JSON.stringify({ok:true, sample: String(typeof v === 'object' ? JSON.stringify(v) : v).slice(0,200), type: typeof v, size: size})); "
                                "}).catch(e => console.log(JSON.stringify({ok:false, err: String(e)})))"
                            )
                            try:
                                proc = subprocess.run(
                                    ["node", "-e", js_code],
                                    capture_output=True,
                                    text=True,
                                    timeout=15,
                                    cwd=str(repo_root),
                                )
                                entry["spawn_ok"] = True
                                stdout = (proc.stdout or "").strip()
                                stderr = (proc.stderr or "").strip()
                                entry["stderr_tail"] = stderr[-300:] if stderr else None
                                # find a JSON line
                                parsed = None
                                for line in reversed(stdout.splitlines()):
                                    line = line.strip()
                                    if line.startswith("{") and line.endswith("}"):
                                        try:
                                            parsed = json.loads(line)
                                            break
                                        except Exception:
                                            continue
                                if parsed is None:
                                    entry["error"] = f"no JSON output (rc={proc.returncode})"
                                else:
                                    entry["parsed_json"] = parsed
                                    if parsed.get("ok"):
                                        entry["sample"] = parsed.get("sample")
                                        size = parsed.get("size", 0) or 0
                                        entry["bytes_or_items"] = size
                                        if size > 0:
                                            entry["passed"] = True
                                        else:
                                            entry["error"] = "empty response"
                                    else:
                                        entry["error"] = parsed.get("err") or "js call failed"
                            except subprocess.TimeoutExpired:
                                entry["error"] = "timeout after 15s"
                            except FileNotFoundError:
                                entry["error"] = "node executable not found"
                        except Exception as e:
                            entry["error"] = f"{type(e).__name__}: {e}"

                        entry["elapsed_ms"] = int((time.time() - t0) * 1000)
                        javascript_results.append(entry)

                    # ---- Build report ----
                    total_elapsed = time.time() - t_start
                    no_sdks = (len(python_results) == 0 and len(javascript_results) == 0)

                    py_pass = sum(1 for e in python_results if e["passed"])
                    py_fail = len(python_results) - py_pass
                    js_pass = sum(1 for e in javascript_results if e["passed"])
                    js_fail = len(javascript_results) - js_pass
                    total_pass = py_pass + js_pass
                    total_fail = py_fail + js_fail
                    overall_pass = (total_fail == 0) and (total_pass > 0)

                    # Markdown report
                    lines = []
                    lines.append("# RAPP SDK Smoke Test Report")
                    lines.append("")
                    lines.append(f"- Repo root: `{repo_root}`")
                    lines.append(f"- Total wall-clock: {total_elapsed:.2f}s")
                    lines.append(f"- Python SDKs: {len(python_results)} ({py_pass} passed, {py_fail} failed)")
                    lines.append(f"- JavaScript SDKs: {len(javascript_results)} ({js_pass} passed, {js_fail} failed)")
                    if no_sdks:
                        lines.append("")
                        lines.append("**No SDKs discovered.**")
                    lines.append("")
                    lines.append("## Summary")
                    lines.append("")
                    lines.append("| SDK | Language | Status | bytes_or_items | reason_if_failed |")
                    lines.append("|-----|----------|--------|----------------|------------------|")
                    for e in python_results + javascript_results:
                        status = "✅" if e["passed"] else "❌"
                        reason = "" if e["passed"] else (e.get("error") or "unknown")
                        lines.append(f"| {e['sdk']} | {e['language']} | {status} | {e['bytes_or_items']} | {reason} |")

                    lines.append("")
                    lines.append("## Python detail")
                    lines.append("")
                    for e in python_results:
                        lines.append(f"### {e['sdk']}")
                        detail = {
                            "import_ok": e["import_ok"],
                            "method_called": e["method_called"],
                            "return_type": e["return_type"],
                            "sample": e["sample"],
                            "error": e["error"],
                            "elapsed_ms": e["elapsed_ms"],
                        }
                        lines.append("


if __name__ == "__main__":
    a = SdksmoketestAgent()
    print(a.perform(query="test"))
