"""
Minimal Model Context Protocol (MCP) server scaffold with stdio transport. Implements the JSON-RPC 2.0 framing MCP requires over stdin/stdout: reads line-delimited JSON requests, dispatches by method, writes JSON responses. Handles three core methods: `initialize` (returns protocol version "2024-11-05" and server capabilities {tools:{}}), `tools/list` (returns the registered tool catalog), and `tools/call` (invokes a tool by name with arguments). Registers ONE starter tool called `ping` that takes an optional `message` string argument and returns `{content:[{type:"text", text:"pong: <message>"}]}` — proves the round-trip works end-to-end. Includes a built-in smoke test mode triggered by `python mcp_server_agent.py --smoke-test` that: (1) spawns the server as a subprocess, (2) sends an `initialize` request and asserts protocolVersion comes back, (3) sends `tools/list` and asserts `ping` is in the catalog, (4) sends `tools/call` with name=ping and asserts the response text starts with "pong:", (5) prints "SMOKE TEST: GREEN" and exits 0, or prints which step failed and exits 1. Uses Python stdlib only (json, sys, subprocess, asyncio not required — synchronous line loop is fine). The perform() method on the agent class returns server status and instructions for wiring it into Claude Desktop or any MCP client. Error responses follow JSON-RPC 2.0 spec with code -32601 for method not found and -32602 for invalid params. Logs go to stderr only — stdout is reserved for protocol traffic. This is a foundation other agents in the brainstem can extend by registering additional tools via a simple `register_tool(name, schema, handler)` function exposed at module level.

Auto-generated by LearnNewAgent on 2026-05-03 14:13.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
import urllib.request
from pathlib import Path

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/mcpserver",
    "version": "1.0.0",
    "display_name": "Mcpserver",
    "description": "Minimal Model Context Protocol (MCP) server scaffold with stdio transport. Implements the JSON-RPC 2.0 framing MCP requires over stdin/stdout: reads line-delimited JSON requests, dispatches by method,",
    "author": "rapp",
    "tags": ["custom"],
    "category": "devtools",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"path": "example path"}},
}


class McpserverAgent(BasicAgent):
    def __init__(self):
        self.name = 'Mcpserver'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number or count value."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        try:
                    import json, os, sys
                    from pathlib import Path

                    action = kwargs.get('action', 'status')
                    server_script = kwargs.get('server_script', 'mcp_server_agent.py')
                    agent_name = kwargs.get('agent_name', 'rapp-mcp-server')

                    # Resolve absolute path to the server script for client config
                    script_path = Path(server_script).resolve()
                    python_exe = sys.executable

                    # Built-in tool catalog (mirrors what the server exposes)
                    registered_tools = [
                        {
                            'name': 'ping',
                            'description': 'Round-trip echo tool. Returns "pong: <message>".',
                            'inputSchema': {
                                'type': 'object',
                                'properties': {
                                    'message': {
                                        'type': 'string',
                                        'description': 'Optional message to echo back.'
                                    }
                                },
                                'required': []
                            }
                        }
                    ]

                    # Claude Desktop config snippet
                    claude_desktop_config = {
                        'mcpServers': {
                            agent_name: {
                                'command': python_exe,
                                'args': [str(script_path)]
                            }
                        }
                    }

                    # OS-specific Claude Desktop config file locations
                    if sys.platform == 'darwin':
                        claude_config_path = '~/Library/Application Support/Claude/claude_desktop_config.json'
                    elif sys.platform.startswith('win'):
                        claude_config_path = '%APPDATA%\\Claude\\claude_desktop_config.json'
                    else:
                        claude_config_path = '~/.config/Claude/claude_desktop_config.json'

                    wiring_instructions = [
                        '1. Ensure Python 3.8+ is installed and `mcp_server_agent.py` is on disk.',
                        '2. Run the smoke test to verify the server: `{} {} --smoke-test`'.format(python_exe, script_path),
                        '3. On success you should see: SMOKE TEST: GREEN',
                        '4. Open your Claude Desktop config file at: {}'.format(claude_config_path),
                        '5. Merge the JSON snippet below into the file (create it if missing).',
                        '6. Restart Claude Desktop. The MCP server "{}" should appear in the tools menu.'.format(agent_name),
                        '7. Test by asking Claude: "Use the ping tool with message=hello". Expected: "pong: hello".',
                        '8. To extend: in mcp_server_agent.py, call register_tool(name, schema, handler) at module level before the server loop starts.',
                    ]

                    generic_client_instructions = [
                        'For non-Claude MCP clients, point the client at this command:',
                        '  command: {}'.format(python_exe),
                        '  args:    [{}]'.format(str(script_path)),
                        'Transport: stdio. Protocol version: 2024-11-05.',
                        'Framing: line-delimited JSON-RPC 2.0 on stdin/stdout. Logs on stderr only.',
                    ]

                    # Verify the server script exists (best-effort, non-fatal)
                    script_exists = script_path.exists()
                    script_size = script_path.stat().st_size if script_exists else 0

                    if action == 'config':
                        payload = {
                            'status': 'ok',
                            'action': 'config',
                            'agent_name': agent_name,
                            'claude_desktop_config_path': claude_config_path,
                            'claude_desktop_config_snippet': claude_desktop_config,
                        }
                        return json.dumps(payload, indent=2)

                    if action == 'tools':
                        payload = {
                            'status': 'ok',
                            'action': 'tools',
                            'tools': registered_tools,
                            'count': len(registered_tools),
                        }
                        return json.dumps(payload, indent=2)

                    # Default: full status + wiring instructions
                    payload = {
                        'status': 'ready' if script_exists else 'script_missing',
                        'agent': agent_name,
                        'transport': 'stdio',
                        'protocol_version': '2024-11-05',
                        'capabilities': {'tools': {}},
                        'jsonrpc': '2.0',
                        'server_script': str(script_path),
                        'server_script_exists': script_exists,
                        'server_script_size_bytes': script_size,
                        'python_executable': python_exe,
                        'registered_tools': registered_tools,
                        'tool_count': len(registered_tools),
                        'error_codes': {
                            'method_not_found': -32601,
                            'invalid_params': -32602,
                        },
                        'smoke_test_command': '{} {} --smoke-test'.format(python_exe, script_path),
                        'claude_desktop': {
                            'config_path': claude_config_path,
                            'config_snippet': claude_desktop_config,
                        },
                        'wiring_instructions': wiring_instructions,
                        'generic_client_instructions': generic_client_instructions,
                        'extension_api': 'register_tool(name: str, schema: dict, handler: callable) -> None',
                        'notes': [
                            'stdout is reserved for JSON-RPC traffic only; do not print to stdout from tool handlers.',
                            'Use sys.stderr for any diagnostic logging.',
                            'Other brainstem agents can import mcp_server_agent and call register_tool() to add tools.',
                        ],
                    }
                    return json.dumps(payload, indent=2)
                except Exception as e:
                    return json.dumps({'status': 'error', 'message': str(e)})


if __name__ == "__main__":
    a = McpserverAgent()
    print(a.perform(query="test"))
