"""
Reads LAB_NOTEBOOK.md from the project root and summarizes the most recent entry. Stdlib only — no external dependencies.

Behavior:
1. Locate LAB_NOTEBOOK.md by walking up from the agent file's directory until found, or fall back to the current working directory. If missing, print a clear error and exit cleanly.
2. Parse the file as Markdown. Treat each top-level "## " heading as one notebook entry. The heading line is the entry's TITLE.
3. The "most recent entry" is the FIRST "## " heading encountered in the file (notebooks are written newest-on-top). If none found, report that and exit.
4. Within that entry's body (lines after its heading, up to the next "## " heading or EOF):
   - DATE: extract the first ISO-style date matching YYYY-MM-DD via re.search. If none, also try common formats like "Mon DD, YYYY" or "DD Mon YYYY". If still none, report "date: unknown".
   - BULLET COUNT: count lines whose lstrip() starts with "- ", "* ", or "+ ". Do not count nested sub-bullets differently — every bullet line counts once.
5. Print a compact human-readable summary to stdout, exactly in this shape:
       Most recent entry
       -----------------
       Title:   <title text with leading "## " stripped>
       Date:    <YYYY-MM-DD or "unknown">
       Bullets: <integer>

Implementation notes:
- Use only stdlib: pathlib, re, sys.
- The agent extends BasicAgent and implements perform(self, **kwargs). kwargs may include an optional 'path' override pointing at a specific notebook file; honor it if provided.
- Return a dict like {"title": ..., "date": ..., "bullets": N, "path": str(path)} so callers can consume it programmatically, AND print the human summary above.
- Be defensive: handle empty files, files with no "## " headings, and files where the first heading has no body.

Auto-generated by LearnNewAgent on 2026-05-03 10:38.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
"""

import json
from datetime import datetime
import re
from pathlib import Path
import hashlib

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/labnotebooksummarize",
    "version": "1.0.0",
    "display_name": "Labnotebooksummarize",
    "description": "Reads LAB_NOTEBOOK.md from the project root and summarizes the most recent entry. Stdlib only — no external dependencies.  Behavior: 1. Locate LAB_NOTEBOOK.md by walking up from the agent file's direc",
    "author": "rapp",
    "tags": ["filesystem", "search", "nlp"],
    "category": "productivity",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {"path": "example path", "query": "example query"}},
}


class LabnotebooksummarizeAgent(BasicAgent):
    def __init__(self):
        self.name = 'Labnotebooksummarize'
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "path": {
                        "type": "string",
                        "description": "File or directory path."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number or count value."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')

        try:
                    import re
                    import json
                    import sys
                    from pathlib import Path

                    override = kwargs.get('path', None)
                    notebook_path = None

                    if override:
                        p = Path(override).expanduser().resolve()
                        if p.is_file():
                            notebook_path = p
                        else:
                            msg = f"Notebook not found at override path: {p}"
                            print(msg)
                            return json.dumps({'status': 'error', 'message': msg})
                    else:
                        # Walk up from this agent file's directory
                        try:
                            start = Path(__file__).resolve().parent
                        except NameError:
                            start = Path.cwd().resolve()

                        candidates = []
                        cur = start
                        while True:
                            candidates.append(cur)
                            if cur.parent == cur:
                                break
                            cur = cur.parent
                        candidates.append(Path.cwd().resolve())

                        for d in candidates:
                            cand = d / "LAB_NOTEBOOK.md"
                            if cand.is_file():
                                notebook_path = cand
                                break

                    if notebook_path is None:
                        msg = "LAB_NOTEBOOK.md not found in any parent directory or current working directory."
                        print(msg)
                        return json.dumps({'status': 'error', 'message': msg})

                    try:
                        text = notebook_path.read_text(encoding='utf-8', errors='replace')
                    except Exception as e:
                        msg = f"Could not read {notebook_path}: {e}"
                        print(msg)
                        return json.dumps({'status': 'error', 'message': msg})

                    lines = text.splitlines()

                    if not lines or not text.strip():
                        msg = "Notebook is empty; no entries to summarize."
                        print(msg)
                        return json.dumps({'status': 'error', 'message': msg, 'path': str(notebook_path)})

                    # Find first "## " heading
                    first_idx = None
                    for i, ln in enumerate(lines):
                        if ln.startswith("## "):
                            first_idx = i
                            break

                    if first_idx is None:
                        msg = "No '## ' headings found in notebook; nothing to summarize."
                        print(msg)
                        return json.dumps({'status': 'error', 'message': msg, 'path': str(notebook_path)})

                    title = lines[first_idx][3:].strip()

                    # Find next "## " heading
                    next_idx = len(lines)
                    for j in range(first_idx + 1, len(lines)):
                        if lines[j].startswith("## "):
                            next_idx = j
                            break

                    body_lines = lines[first_idx + 1:next_idx]
                    body_text = "\n".join(body_lines)

                    # Date extraction
                    date_str = None
                    m = re.search(r'\b(\d{4}-\d{2}-\d{2})\b', body_text)
                    if m:
                        date_str = m.group(1)
                    else:
                        m2 = re.search(r'\b([A-Z][a-z]{2})\s+(\d{1,2}),\s+(\d{4})\b', body_text)
                        if m2:
                            try:
                                from datetime import datetime
                                dt = datetime.strptime(f"{m2.group(1)} {m2.group(2)} {m2.group(3)}", "%b %d %Y")
                                date_str = dt.strftime("%Y-%m-%d")
                            except Exception:
                                date_str = f"{m2.group(1)} {m2.group(2)}, {m2.group(3)}"
                        else:
                            m3 = re.search(r'\b(\d{1,2})\s+([A-Z][a-z]{2})\s+(\d{4})\b', body_text)
                            if m3:
                                try:
                                    from datetime import datetime
                                    dt = datetime.strptime(f"{m3.group(1)} {m3.group(2)} {m3.group(3)}", "%d %b %Y")
                                    date_str = dt.strftime("%Y-%m-%d")
                                except Exception:
                                    date_str = f"{m3.group(1)} {m3.group(2)} {m3.group(3)}"

                    if not date_str:
                        date_str = "unknown"

                    # Bullet count
                    bullets = 0
                    for bl in body_lines:
                        stripped = bl.lstrip()
                        if stripped.startswith("- ") or stripped.startswith("* ") or stripped.startswith("+ "):
                            bullets += 1

                    print("Most recent entry")
                    print("-----------------")
                    print(f"Title:   {title}")
                    print(f"Date:    {date_str}")
                    print(f"Bullets: {bullets}")

                    return json.dumps({
                        'status': 'ok',
                        'title': title,
                        'date': date_str,
                        'bullets': bullets,
                        'path': str(notebook_path),
                    })
                except Exception as e:
                    import json
                    return json.dumps({'status': 'error', 'message': str(e)})


if __name__ == "__main__":
    a = LabnotebooksummarizeAgent()
    print(a.perform(query="test"))
